const fs=require('fs'),path=require('path'),assert=require('node:assert/strict');
const {pathToFileURL}=require('url');
const swc=require('next/dist/build/swc');
const {PGlite}=require('@electric-sql/pglite');
(async()=>{
 for(const f of ['pages/my-hr.js','pages/api/hr.js','pages/api/hr-records.js','components/HRRecords.js'])await swc.transform(fs.readFileSync(path.join(__dirname,'..',f),'utf8'),{filename:f,jsc:{parser:{syntax:'ecmascript',jsx:true}}});
 const {canViewStaffPage}=await import(pathToFileURL(path.join(__dirname,'..','lib/staff-access.mjs')));
 for(const p of ['/admin','/pos','/warehouse','/operations','/payroll'])assert.equal(canViewStaffPage('hr',p),false);
 const {validateLeave,hrSchema,reviewLeave}=await import(pathToFileURL(path.join(__dirname,'..','lib/hr-workflow.mjs')));
 const {setupRecords,recordsReady,validateFile,canReadDocument,medicalDecision}=await import(pathToFileURL(path.join(__dirname,'..','lib/hr-records.mjs')));
 const employee={id:1,role:'warehouse_clerk'},gm={id:2,role:'general_manager'},admin={id:3,role:'admin'},hr={id:4,role:'hr'};
 const db=new PGlite();await db.exec('CREATE TABLE customers(id INTEGER PRIMARY KEY); INSERT INTO customers VALUES(1),(2),(3),(4);');for(const q of hrSchema)await db.exec(q);
 await db.query("INSERT INTO hr_leave_requests(employee_id,start_date,end_date,leave_type,reason) VALUES(1,'2026-09-01','2026-09-02','Annual','Test')");
 await db.query('BEGIN');await setupRecords(db,hr);await db.query('COMMIT');assert.equal(await recordsReady(db),true);
 assert.equal((await db.query('SELECT status FROM hr_leave_requests')).rows[0].status,'PENDING_HR');
 await assert.rejects(reviewLeave(db,gm,{id:1,decision:'APPROVE',note:'Skip HR'}));
 await assert.rejects(reviewLeave(db,admin,{id:1,decision:'APPROVE',note:'Skip'}));
 await assert.rejects(reviewLeave(db,{id:1,role:'hr'},{id:1,decision:'FORWARD',note:'Own'}));
 await reviewLeave(db,hr,{id:1,decision:'FORWARD',note:'Checked'});
 await reviewLeave(db,gm,{id:1,decision:'APPROVE',note:'Approved'});
 await assert.rejects(reviewLeave(db,gm,{id:1,decision:'REJECT',note:'Late change'}));
 assert.equal((await db.query('SELECT status FROM hr_leave_requests')).rows[0].status,'APPROVED');
 await db.query('BEGIN');await setupRecords(db,hr);await db.query('COMMIT');
 assert.equal((await db.query('SELECT status FROM hr_leave_requests')).rows[0].status,'APPROVED');
 assert.equal((await db.query('SELECT * FROM hr_events')).rows.length,3);
 assert.throws(()=>validateLeave({startDate:'2026-02-30',endDate:'2026-03-01',leaveType:'Annual',reason:'test'}));
 const document={employee_id:1,application_id:null};assert.equal(canReadDocument(employee,document),true);assert.equal(canReadDocument({id:8,role:'cashier'},document),false);assert.equal(canReadDocument(gm,document),false);assert.equal(canReadDocument(hr,document),true);assert.equal(canReadDocument(gm,{...document,application_id:2}),true);
 const sample={name:'sample.pdf',mime:'application/pdf',category:'EDUCATION',content:Buffer.from('%PDF-1.4\nTest document\n%%EOF').toString('base64')};
 assert.equal(validateFile(sample).mime,'application/pdf');assert.throws(()=>validateFile({...sample,category:'PHOTO'}));assert.throws(()=>validateFile({...sample,mime:'image/png'}));assert.throws(()=>validateFile({...sample,content:Buffer.from('<script>alert(1)</script>').toString('base64')}));assert.throws(()=>validateFile({...sample,content:Buffer.alloc(2097153).toString('base64')}));
 const app={employee_id:1,status:'DRAFT'};assert.equal(medicalDecision(hr,app,'FORWARD','Reviewed'),'PENDING_MANAGER');assert.throws(()=>medicalDecision(gm,app,'APPROVE','Skip'));assert.throws(()=>medicalDecision({id:1,role:'hr'},app,'FORWARD','Own'));assert.equal(medicalDecision(gm,{...app,status:'PENDING_MANAGER',hr_id:4},'APPROVE','ok'),'APPROVED');assert.throws(()=>medicalDecision(admin,{...app,status:'PENDING_MANAGER',hr_id:4},'APPROVE','ok'));
 const bytes=validateFile(sample).bytes;await db.query("INSERT INTO hr_documents(employee_id,category,name,mime,bytes,uploaded_by) VALUES(1,'EDUCATION','sample.pdf','application/pdf',$1,4)",[bytes]);assert.deepEqual(Buffer.from((await db.query('SELECT bytes FROM hr_documents')).rows[0].bytes),bytes);
 // Exercise the actual HTTP handler with isolated PostgreSQL and injected sessions.
 await db.exec("ALTER TABLE customers ADD name TEXT DEFAULT 'Test staff'; ALTER TABLE customers ADD role TEXT DEFAULT 'warehouse_clerk';");
 const records=await import(pathToFileURL(path.join(__dirname,'..','lib/hr-records.mjs')));
 const access=await import(pathToFileURL(path.join(__dirname,'..','lib/staff-access.mjs')));
 const compiled=await swc.transform(fs.readFileSync(path.join(__dirname,'..','pages/api/hr-records.js'),'utf8'),{filename:'hr-records.js',jsc:{parser:{syntax:'ecmascript'}},module:{type:'commonjs'}});
 const mod={exports:{}};let session=hr;
 const client={query:(...a)=>db.query(...a),release:()=>{}};
 new Function('require','module','exports',compiled.code)(name=>name.endsWith('/db')?{getPool:()=>({connect:async()=>client})}:name.endsWith('/auth')?{readSession:async()=>session}:name.includes('staff-access')?access:records,mod,mod.exports);
 async function call(who,body,query={},headers={}){session=who;const r={statusCode:200,headers:{},setHeader(k,v){this.headers[k]=v;},status(n){this.statusCode=n;return this;},json(b){this.body=b;return this;},send(b){this.body=b;return this;},end(){return this;}};await mod.exports.default({method:body?'POST':'GET',body,query,headers:{'content-type':'application/json',...headers}},r);return r;}
 assert.equal((await call(null)).statusCode,401);assert.equal((await call({id:1,role:'customer'})).statusCode,403);
 assert.equal((await call({id:8,role:'cashier'},null,{document:1})).statusCode,404);
 assert.equal((await call(gm,null,{document:1})).statusCode,404);
 assert.deepEqual(Buffer.from((await call(employee,null,{document:1})).body),bytes);
 assert.equal((await call(hr,{action:'UPLOAD',employeeId:1,...sample},{},{'sec-fetch-site':'cross-site'})).statusCode,403);
 assert.equal((await call(employee,{action:'UPLOAD',employeeId:1,...sample})).statusCode,400);
 assert.equal((await call(hr,{action:'UPLOAD',employeeId:1,...sample})).statusCode,200);
 assert.equal((await call({id:8,role:'cashier'})).body.documents.length,0);
 assert.equal((await call(employee,{action:'CREATE_MEDICAL',provider:'Test insurer',plan:'Test plan'})).statusCode,200);
 assert.equal((await call(hr,{action:'MEDICAL_DECIDE',id:1,decision:'FORWARD',note:'Reviewed'})).statusCode,400);
 assert.equal((await call(hr,{action:'UPLOAD',employeeId:1,applicationId:1,...sample,category:'MEDICAL_SUPPORT'})).statusCode,200);
 assert.equal((await call(hr,{action:'UPLOAD',employeeId:2,applicationId:1,...sample,category:'MEDICAL_SUPPORT'})).statusCode,400);
 assert.equal((await call(hr,{action:'MEDICAL_DECIDE',id:1,decision:'FORWARD',note:'Reviewed'})).statusCode,200);
 assert.equal((await call(hr,{action:'UPLOAD',employeeId:1,applicationId:1,...sample,category:'MEDICAL_SUPPORT'})).statusCode,400);
 assert.equal((await call(admin,{action:'MEDICAL_DECIDE',id:1,decision:'APPROVE',note:'No'})).statusCode,400);
 assert.equal((await call(gm,{action:'MEDICAL_DECIDE',id:1,decision:'APPROVE',note:'Approved'})).statusCode,200);
 assert.equal((await call(hr,{action:'UPLOAD',employeeId:1,applicationId:1,...sample,category:'MEDICAL_APPROVAL'})).statusCode,200);
 assert.equal((await call(gm)).body.documents.every(d=>d.application_id!==null),true);
 await db.close();console.log('PASS: JSX compile; schema migration; HR → GM final leave approval; API authentication and isolation; upload validation and storage; medical supporting-document requirement, locking and final approval.');
})().catch(e=>{console.error(e);process.exit(1)});

