import {useEffect,useRef,useState} from 'react';
const money=n=>'KSh '+(Number(n||0)/100).toLocaleString('en-KE',{minimumFractionDigits:2,maximumFractionDigits:2});
const today=()=>new Date().toLocaleDateString('en-CA',{timeZone:'Africa/Nairobi'});
function csv(name,rows){const text=rows.map(row=>row.map(v=>'"'+String(v??'').replace(/^[=+@-]/,"'$&").replaceAll('"','""')+'"').join(',')).join('\r\n');const url=URL.createObjectURL(new Blob(['\ufeff'+text],{type:'text/csv;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download=name;a.click();URL.revokeObjectURL(url);}
export default function FinanceLedger({role}){
 const [data,setData]=useState(null),[error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false),[period,setPeriod]=useState(()=>today().slice(0,7));
 const [bill,setBill]=useState({kind:'SUPPLIER',payee:'',reference:'',description:'',amount:'',dueOn:'',period:today().slice(0,7)}),[salary,setSalary]=useState({payrollId:'',dueOn:''}),[target,setTarget]=useState({employeeId:'',amount:'',note:''}),[decision,setDecision]=useState({id:'',note:''}),[payment,setPayment]=useState({id:'',amount:'',method:'Bank',reference:'',paidOn:today(),confirmPaid:false});
 const keys=useRef(new Map());const finance=['admin','finance'].includes(role),management=role!=='cashier';
 async function load(){const r=await fetch('/api/finance-ledger?period='+period,{cache:'no-store'}),j=await r.json();if(!r.ok)throw Error(j.error);setData(j);}
 useEffect(()=>{load().catch(e=>setError(e.message));},[period]);
 async function send(b,reset){if(busy)return;setBusy(true);setError('');setNotice('');const key=JSON.stringify(b);if(!keys.current.has(key))keys.current.set(key,crypto.randomUUID());try{const r=await fetch('/api/finance-ledger',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...b,requestKey:keys.current.get(key)})}),j=await r.json();if(!r.ok)throw Error(j.error);await load();reset?.();setNotice('Saved. No money was transferred.');}catch(e){setError(e.message);}finally{setBusy(false);}}
 const waiting=data?.bills?.filter(b=>(role==='general_manager'&&b.status==='PENDING_MANAGER')||(role==='admin'&&b.status==='PENDING_ADMIN'))||[];
 const kpis=(data?.employees||[]).map(u=>{const p=data.pos.find(x=>String(x.cashier_id)===String(u.id)),r=data.refunds.find(x=>String(x.cashier_id)===String(u.id)),a=data.commercial.find(x=>String(x.salesperson_id)===String(u.id)),t=data.targets.find(x=>String(x.employee_id)===String(u.id));return {...u,net:(Number(p?.amount||0)-Number(r?.amount||0))*100,sales:Number(p?.sales||0),refunds:Number(r?.amount||0)*100,target:Number(t?.target_cents||0),invoiced:Number(a?.invoiced||0)*100,quotes:Number(a?.quotations||0),converted:Number(a?.converted||0),collected:Number(a?.collected||0)*100};});
 const paidTotal=(data?.totals||[]).reduce((s,x)=>s+Number(x.paid_cents),0);let offset=0;const colors=['#77c847','#e9be55','#729ce3'];const stops=(data?.totals||[]).map((x,i)=>{const start=offset;offset+=paidTotal?Number(x.paid_cents)/paidTotal*100:0;return `${colors[i%3]} ${start}% ${offset}%`;});
 return <div className="ledger">
 <section className="financeCards" aria-label="Finance functions"><h2>Finance workspace</h2><p>Choose a function to continue.</p><div className="cardGrid">{(finance?[['Supplier and government bills','Record supplier invoices and assessed statutory obligations'],['Salary payments','Prepare payments from approved payroll'],['Payment settlements','Record completed external payments'],['Payment reports','Review liabilities, payments and exports'],['Sales targets & KPIs','Set and review salesperson performance'],['Finance audit trail','Review finance decisions']]:[['Payment reports','View finance reports and approved liabilities'],['Sales targets & KPIs','View your sales performance']]).map(([title,detail])=><a key={title} href={'#'+title.toLowerCase().replaceAll(/[^a-z0-9]+/g,'-')}><strong>{title}</strong><span>{detail} →</span></a>)}</div></section>
 {error&&<p role="alert">{error}</p>}{notice&&<p role="status">{notice}</p>}
 {!data&&<p>Loading supplier, payroll and performance tools…</p>}
 {data&&!data.ready&&<section className="panel"><h2>Enable extended finance</h2><p>Initialise empty supplier liabilities, salary settlements, statutory obligations and targets. Existing payroll, stock and sales are unchanged.</p>{role==='admin'?<button disabled={busy} onClick={()=>send({action:'SETUP'})}>Initialise extended finance</button>:<p>Administrator setup is required.</p>}</section>}
 {data?.ready&&<>
 {finance&&<form className="panel" onSubmit={e=>{e.preventDefault();send({action:'BILL',...bill},()=>setBill({...bill,reference:'',amount:'',description:''}));}}><h2>Supplier and statutory bills</h2><p>Record a supplier invoice or an assessed government obligation. General manager review → administrator approval → finance records external payment. This does not receive stock or calculate tax.</p>
 <label>Liability type<select value={bill.kind} onChange={e=>setBill({...bill,kind:e.target.value})}><option value="SUPPLIER">Supplier bill</option><option value="STATUTORY">Government levy / statutory obligation</option></select></label>
 <label>Supplier or authority<input required maxLength={160} placeholder="Supplier name, KRA, NSSF, SHA or county authority" value={bill.payee} onChange={e=>setBill({...bill,payee:e.target.value})}/></label>
 <label>Invoice / assessment reference<input required maxLength={120} value={bill.reference} onChange={e=>setBill({...bill,reference:e.target.value})}/></label><label>Amount (KSh)<input required type="number" min="0.01" step="0.01" value={bill.amount} onChange={e=>setBill({...bill,amount:e.target.value})}/></label>
 <label>Accounting month<input required type="month" value={bill.period} onChange={e=>setBill({...bill,period:e.target.value})}/></label><label>Due date<input required type="date" value={bill.dueOn} onChange={e=>setBill({...bill,dueOn:e.target.value})}/></label>
 <label>Supporting reference and details<textarea required maxLength={1000} placeholder="Purchase order / assessment reference, tax type and period; retain the original document securely." value={bill.description} onChange={e=>setBill({...bill,description:e.target.value})}/></label>
 <p>Enter statutory amounts and deadlines from verified assessments or accountant instructions. No return is filed and no government payment is sent.</p><button disabled={busy}>Submit liability for review</button></form>}
 {finance&&<form className="panel" onSubmit={e=>{e.preventDefault();send({action:'SALARY',...salary},()=>setSalary({payrollId:'',dueOn:''}));}}><h2>Employee salary payments</h2><p>Import an already approved net salary once. Existing payroll approvals are retained. Pay the employee through your bank or M-Pesa, then record its reference in Payment settlements.</p><label>Approved unpaid payroll<select required value={salary.payrollId} onChange={e=>setSalary({...salary,payrollId:e.target.value})}><option value="">Select approved payroll</option>{data.payroll.map(p=><option key={p.id} value={p.id}>{p.employee_name} · {p.period} · {money(Number(p.net)*100)}</option>)}</select></label><label>Payment due date<input required type="date" value={salary.dueOn} onChange={e=>setSalary({...salary,dueOn:e.target.value})}/></label><button disabled={busy||!data.payroll.length}>Add approved salary to payments</button>{!data.payroll.length&&<p>No unimported approved salary records. Prepare and approve payroll first.</p>}</form>}
 {['admin','general_manager'].includes(role)&&<form className="panel" onSubmit={e=>e.preventDefault()}><h2>Review payment liabilities</h2><label>Pending liability<select value={decision.id} onChange={e=>setDecision({...decision,id:e.target.value})}><option value="">Select liability</option>{waiting.map(b=><option key={b.id} value={b.id}>#{b.id} · {b.kind} · {b.payee} · {money(b.amount_cents)}</option>)}</select></label>{data.bills.filter(b=>String(b.id)===decision.id).map(b=><p key={b.id}>{b.reference} · due {String(b.due_on).slice(0,10)} · {b.description}</p>)}<label>Decision reason<textarea required maxLength={1000} value={decision.note} onChange={e=>setDecision({...decision,note:e.target.value})}/></label><button disabled={busy||!decision.id||!decision.note.trim()} onClick={()=>send({action:role==='admin'?'APPROVE':'REVIEW',...decision},()=>setDecision({id:'',note:''}))}>{role==='admin'?'Approve liability':'Recommend to administrator'}</button><button disabled={busy||!decision.id||!decision.note.trim()} onClick={()=>send({action:'REJECT',...decision},()=>setDecision({id:'',note:''}))}>Reject liability</button><p>Decisions are audited. Settled records cannot be edited or deleted.</p></form>}
 {finance&&<form className="panel" onSubmit={e=>{e.preventDefault();send({action:'SETTLE',...payment},()=>setPayment({...payment,amount:'',reference:'',confirmPaid:false}));}}><h2>Payment settlements</h2><label>Approved unpaid liability<select required value={payment.id} onChange={e=>setPayment({...payment,id:e.target.value})}><option value="">Select liability</option>{data.bills.filter(b=>b.status==='APPROVED'&&Number(b.balance_cents)>0).map(b=><option key={b.id} value={b.id}>#{b.id} · {b.kind} · {b.payee} · remaining {money(b.balance_cents)}</option>)}</select></label><label>Amount paid (KSh)<input required type="number" min="0.01" step="0.01" value={payment.amount} onChange={e=>setPayment({...payment,amount:e.target.value})}/></label><label>Payment method<select value={payment.method} onChange={e=>setPayment({...payment,method:e.target.value})}>{['Bank','M-Pesa','Cash','Card'].map(m=><option key={m}>{m}</option>)}</select></label><label>Unique bank / payment receipt reference<input required maxLength={120} value={payment.reference} onChange={e=>setPayment({...payment,reference:e.target.value})}/></label><label>Date paid<input required type="date" max={today()} value={payment.paidOn} onChange={e=>setPayment({...payment,paidOn:e.target.value})}/></label><label><input type="checkbox" required checked={payment.confirmPaid} onChange={e=>setPayment({...payment,confirmPaid:e.target.checked})}/> I confirm this payment was completed externally. This button does not send money.</label><button disabled={busy}>Record completed payment</button></form>}
 {management&&<section className="panel"><h2>Liabilities and payment reports</h2><p>Approved liabilities only in totals; all dates. These are payment registers, not a balance sheet, profit-and-loss statement or bank reconciliation.</p><div className="reportTable"><table><thead><tr><th>Type</th><th>Approved</th><th>Paid</th><th>Outstanding</th><th>Overdue</th></tr></thead><tbody>{data.totals.map(t=><tr key={t.kind}><td>{t.kind}</td><td>{money(t.total_cents)}</td><td>{money(t.paid_cents)}</td><td>{money(t.outstanding_cents)}</td><td>{money(t.overdue_cents)}</td></tr>)}</tbody></table></div>{!data.totals.length&&<p>No approved liabilities yet.</p>}
 {paidTotal>0&&<><div className="pie" role="img" aria-label={'Recorded outgoing payments: '+data.totals.map(t=>t.kind+' '+money(t.paid_cents)).join(', ')} style={{background:`conic-gradient(${stops.join(',')})`}}/>{data.totals.map((t,i)=><p key={t.kind} style={{color:colors[i%3]}}>{t.kind}: {money(t.paid_cents)}</p>)}</>}
 <h3>Outgoing payments — last six months</h3>{data.monthly.map(m=><div key={m.month}><span>{m.month} · {money(m.amount_cents)}</span><div className="bar" style={{width:Math.max(2,Number(m.amount_cents)/Math.max(...data.monthly.map(x=>Number(x.amount_cents)))*100)+'%'}}/></div>)}
 <h3>Liability register (latest 500)</h3><button onClick={()=>csv('shilatech-liabilities.csv',[['ID','Type','Payee','Reference','Period','Due','Amount KSh','Paid KSh','Balance KSh','Status'],...data.bills.map(b=>[b.id,b.kind,b.payee,b.reference,b.period,String(b.due_on).slice(0,10),Number(b.amount_cents)/100,Number(b.paid_cents)/100,Number(b.balance_cents)/100,b.status])])}>Download liability register CSV</button><div className="reportTable"><table><thead><tr><th>Payee / reference</th><th>Due</th><th>Amount / balance</th><th>Status</th></tr></thead><tbody>{data.bills.map(b=><tr key={b.id}><td>#{b.id} {b.kind} · {b.payee}<br/>{b.reference}<br/>{b.description}</td><td>{String(b.due_on).slice(0,10)}</td><td>{money(b.amount_cents)}<br/>{money(b.balance_cents)}</td><td>{b.status}</td></tr>)}</tbody></table></div>
 <h3>Payment receipts (latest 500)</h3><button onClick={()=>csv('shilatech-payments.csv',[['ID','Payee','Type','Paid on','Amount KSh','Method','Reference'],...data.settlements.map(p=>[p.id,p.payee,p.kind,String(p.paid_on).slice(0,10),Number(p.amount_cents)/100,p.method,p.reference])])}>Download payments CSV</button>{data.settlements.map(p=><p key={p.id}>{String(p.paid_on).slice(0,10)} · {p.payee} · {money(p.amount_cents)} · {p.method} · {p.reference}</p>)}</section>}
 <section className="panel"><h2>Sales targets and KPIs</h2><label>Report month<input type="month" value={period} onChange={e=>{if(e.target.value)setPeriod(e.target.value);}}/></label><p>Targets measure counter sales less approved refund credits recorded in this month. Commercial invoice values are shown separately to avoid double counting. Quotation conversion counts invoices issued from this month's quotations, including later conversions.</p>{(!data.posAvailable||!data.refundsAvailable)&&<p role="alert">Counter or refund records unavailable. Target attainment is not verified.</p>}
 {kpis.map(k=><article key={k.id} className="kpi"><h3>{k.name}</h3><p>Counter sales net of refund credits: {money(k.net)} · {k.sales} sales · Refund credits {money(k.refunds)}</p><p>Target: {k.target?money(k.target):'Not assigned'} · Attainment: {k.target&&data.posAvailable&&data.refundsAvailable?(k.net/k.target*100).toFixed(1)+'%':'Not available'}</p>{k.target>0&&<progress aria-label={'Target attainment for '+k.name} value={Math.max(0,k.net)} max={k.target}/>}<p>Commercial invoices: {money(k.invoiced)} · Collections against those invoices to date: {money(k.collected)}<br/>Quotations: {k.quotes} · Converted: {k.converted} · Conversion: {k.quotes?(100*k.converted/k.quotes).toFixed(1)+'%':'—'}</p></article>)}{!kpis.length&&<p>No sales employees available.</p>}
 <button onClick={()=>csv('sales-kpis-'+period+'.csv',[['Employee','Month','Counter net KSh','Target KSh','Commercial invoices KSh','Quotations','Converted'],...kpis.map(k=>[k.name,period,k.net/100,k.target/100,k.invoiced/100,k.quotes,k.converted])])}>Download KPI report CSV</button>
 {role==='admin'&&<form onSubmit={e=>{e.preventDefault();send({action:'TARGET',period,...target});}}><h3>Set monthly counter-sales target</h3><label>Sales employee<select required value={target.employeeId} onChange={e=>setTarget({...target,employeeId:e.target.value})}><option value="">Select salesperson</option>{data.employees.map(u=><option key={u.id} value={u.id}>{u.name}</option>)}</select></label><label>Target (KSh)<input required type="number" min="0.01" step="0.01" value={target.amount} onChange={e=>setTarget({...target,amount:e.target.value})}/></label><label>Reason<textarea required maxLength={1000} value={target.note} onChange={e=>setTarget({...target,note:e.target.value})}/></label><button disabled={busy}>Save target for {period}</button></form>}</section>
 {management&&<section className="panel"><h2>Finance audit trail</h2><p>Latest 200 recorded decisions and changes.</p>{data.events.map(e=><p key={e.id}>{String(e.created_at).slice(0,19)} · {e.actor_name} · {e.action} #{e.entity_id}<br/>{e.note}</p>)}</section>}
 </>}
 <style jsx>{`.ledger{color:#e7ede4;line-height:1.65}.panel{padding:22px;margin:20px 0;border:1px solid #39512e;border-radius:10px;max-width:1000px;background:rgba(6,14,5,.9)}h2,h3{color:#83ce51}label{display:block;margin:14px 0}input,select,textarea{display:block;width:100%;box-sizing:border-box;padding:10px;background:#101910;color:white;border:1px solid #53654b}input[type=checkbox]{display:inline;width:auto}button{padding:11px 16px;background:#65bd35;color:#071003;border:0;margin:4px;cursor:pointer}button:disabled{opacity:.5;cursor:not-allowed}.reportTable{overflow-x:auto}table{width:100%;border-collapse:collapse}td,th{text-align:left;padding:10px;border-bottom:1px solid #39512e;overflow-wrap:anywhere}.pie{width:150px;height:150px;border-radius:50%;margin:20px 0}.bar{height:18px;background:#77c847;margin:5px 0 18px}.kpi{border-bottom:1px solid #39512e;padding:12px 0}progress{width:100%;accent-color:#77c847}`}</style>
 </div>;
}
