import {useEffect,useState} from 'react';
const categories={PHOTO:'Employee photo',GOOD_CONDUCT:'Good conduct certificate',EDUCATION:'Education qualification certificate',MEDICAL_SUPPORT:'Medical insurance supporting document',MEDICAL_APPROVAL:'Medical insurance approval document'};
export default function HRRecords({user}){
 const [data,setData]=useState({documents:[],applications:[],events:[]}),[error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false),[employee,setEmployee]=useState(String(user.userId)),[category,setCategory]=useState('PHOTO'),[application,setApplication]=useState(''),[file,setFile]=useState(null),[inputKey,setInputKey]=useState(0),[notes,setNotes]=useState({}),[form,setForm]=useState({provider:'',plan:'',notes:''});
 const hr=['hr','admin'].includes(user.role);
 async function load(){const r=await fetch('/api/hr-records',{cache:'no-store'});const j=await r.json();if(!r.ok)throw Error(j.error);setData(j);}
 useEffect(()=>{load().catch(e=>setError(e.message));},[]);
 async function send(body){setBusy(true);setError('');setNotice('');try{const r=await fetch('/api/hr-records',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const j=await r.json();if(!r.ok)throw Error(j.error);await load();setNotice('Saved successfully.');return true;}catch(e){setError(e.message);return false;}finally{setBusy(false);}}
 async function upload(e){e.preventDefault();if(!file)return;setError('');if(file.size>2*1024*1024){setError('Maximum file size is 2 MB.');return;}try{const content=await new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(String(r.result).split(',')[1]);r.onerror=()=>reject(Error('Could not read the file.'));r.readAsDataURL(file);});if(await send({action:'UPLOAD',employeeId:employee,category,applicationId:category.startsWith('MEDICAL_')?application:null,name:file.name,mime:file.type,content})){setFile(null);setInputKey(k=>k+1);}}catch(e){setError(e.message);}}
 return <div className="records">
 {error&&<p role="alert">{error}</p>}{notice&&<p role="status">{notice}</p>}
 <section id="documents"><h2>Employee documents</h2><p>Private staff records. Downloads require sign-in and are recorded in the audit log. Use sample documents while testing; upload only information necessary for the selected purpose.</p>
 {hr&&<label>Staff member<select value={employee} onChange={e=>{setEmployee(e.target.value);setApplication('');}}>{user.staff.map(s=><option key={s.id} value={s.id}>{s.name} · {s.email}</option>)}</select></label>}
 {hr?<form onSubmit={upload}><h3>Upload a document</h3><label>Document type<select value={category} onChange={e=>{setCategory(e.target.value);setFile(null);setInputKey(k=>k+1);}}>{Object.entries(categories).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></label>
 {category.startsWith('MEDICAL_')&&<label>Medical application<select required value={application} onChange={e=>setApplication(e.target.value)}><option value="">Select application</option>{data.applications.filter(a=>String(a.employee_id)===employee&&a.status===(category==='MEDICAL_SUPPORT'?'DRAFT':'APPROVED')).map(a=><option key={a.id} value={a.id}>#{a.id} · {a.provider} · {a.plan}</option>)}</select></label>}
 <label>File (maximum 2 MB)<input key={inputKey} required type="file" accept={category==='PHOTO'?'.png,.jpg,.jpeg':'.pdf,.png,.jpg,.jpeg'} onChange={e=>setFile(e.target.files?.[0]||null)}/></label><p>PNG/JPEG for photos; PDF, PNG or JPEG for certificates. Up to 20 documents per employee in this test environment. Files are downloaded, not opened inside the portal. Malware scanning is not connected.</p><button disabled={busy||!file}>Upload private document</button></form>:<p>Ask HR to upload or correct your documents.</p>}
 {!data.documents.filter(d=>!hr||String(d.employee_id)===employee).length&&<p>No documents available.</p>}
 {data.documents.filter(d=>!hr||String(d.employee_id)===employee).map(d=><p key={d.id}>{d.employee_name} · {categories[d.category]} · <a href={'/api/hr-records?document='+d.id}>{d.name} — Download</a></p>)}</section>
 <section id="medical"><h2>Medical insurance applications</h2><p>Create a draft, attach the insurer’s required supporting documents, then HR forwards it to the general manager. Internal approval does not enrol anyone with an insurer or confirm cover. Do not include diagnoses or unnecessary medical records.</p>
 <form onSubmit={async e=>{e.preventDefault();if(await send({action:'CREATE_MEDICAL',employeeId:employee,...form}))setForm({provider:'',plan:'',notes:''});}}><h3>{hr?'New application for selected staff member':'My new application'}</h3><label>Insurance provider<input required maxLength={160} value={form.provider} onChange={e=>setForm({...form,provider:e.target.value})}/></label><label>Plan / scheme<input required maxLength={160} value={form.plan} onChange={e=>setForm({...form,plan:e.target.value})}/></label><label>Administrative notes (optional)<textarea maxLength={1000} value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})}/></label><button disabled={busy}>Create application draft</button></form>
 {!data.applications.length&&<p>No medical applications yet.</p>}{data.applications.map(a=>{const own=String(a.employee_id)===String(user.userId);const forward=user.role==='hr'&&a.status==='DRAFT';const decide=user.role==='general_manager'&&a.status==='PENDING_MANAGER';return <article key={a.id}><h3>#{a.id} · {a.employee_name}</h3><p>{a.provider} · {a.plan} · {a.status.replaceAll('_',' ')}</p><p>{a.notes}</p>{data.documents.filter(d=>String(d.application_id)===String(a.id)).map(d=><p key={d.id}><a href={'/api/hr-records?document='+d.id}>{categories[d.category]}: {d.name}</a></p>)}{!own&&(forward||decide)&&<><label>Medical review note<textarea maxLength={1000} value={notes[a.id]||''} onChange={e=>setNotes({...notes,[a.id]:e.target.value})}/></label><button disabled={busy||!notes[a.id]?.trim()} onClick={()=>send({action:'MEDICAL_DECIDE',id:a.id,decision:forward?'FORWARD':'APPROVE',note:notes[a.id]})}>{forward?'Forward to general manager':'Approve application internally'}</button>{decide&&<button disabled={busy||!notes[a.id]?.trim()} onClick={()=>send({action:'MEDICAL_DECIDE',id:a.id,decision:'REJECT',note:notes[a.id]})}>Reject application</button>}</>}{a.status==='APPROVED'&&<p>Internal approval recorded. HR can now attach approval documents. Confirm enrolment separately with the insurer.</p>}{data.events.filter(e=>String(e.application_id)===String(a.id)).map(e=><p key={e.id}><small>{e.actor_name} · {e.action} · {e.note}</small></p>)}</article>;})}</section>
 <style jsx>{`.records{color:#e7ede4}section{padding-top:24px}h2,h3,a{color:#70c342}form,article{max-width:760px;border:1px solid #405338;padding:20px;margin:20px 0}label{display:block;margin:12px 0}input,select,textarea{display:block;width:100%;box-sizing:border-box;padding:10px;background:#101910;color:white;border:1px solid #53654b}button{padding:12px;background:#65bd35;color:#071003;border:0;margin:6px;cursor:pointer}button:disabled{opacity:.5;cursor:not-allowed}a{overflow-wrap:anywhere}`}</style>
 </div>;
}
