import {useEffect,useRef,useState} from 'react';
import Layout from '../components/Layout';
const label=s=>s.replaceAll('_',' ').toLowerCase();
export default function Approvals(){
 const [data,setData]=useState(null),[kind,setKind]=useState(''),[targetId,setTarget]=useState(''),[reason,setReason]=useState(''),[payload,setPayload]=useState({}),[review,setReview]=useState({}),[error,setError]=useState(''),[message,setMessage]=useState(''),[busy,setBusy]=useState(false);
 const key=useRef(null),sending=useRef(false);
 async function load(){try{const r=await fetch('/api/approvals');const j=await r.json();if(!r.ok)throw new Error(j.error);setData(j);setKind(k=>k||j.kinds[0]||'');}catch(e){setError(e.message);}}
 useEffect(()=>{load();},[]);
 function changePayload(k,v){setPayload(p=>({...p,[k]:v}));key.current=null;}
 async function send(body){if(sending.current)return;sending.current=true;setBusy(true);setError('');setMessage('');try{const r=await fetch('/api/approvals',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const j=await r.json();if(!r.ok)throw new Error(j.error);setMessage(body.action==='CREATE'?'Request submitted. No stock, price or sale has changed.':body.action==='RECORD_PAYOUT'?'External payout recorded. No money was sent by this website.':'Decision recorded.');if(body.action==='CREATE'){setTarget('');setReason('');setPayload({});key.current=null;}await load();}catch(e){setError(e.message);}finally{sending.current=false;setBusy(false);}}
 const source=payload.source||'POS';
 const list=kind==='PRICE_CHANGE'?data?.targets.products:kind==='STOCK_ADJUSTMENT'?data?.targets.batches:kind==='GARAGE_CORRECTION'?data?.targets.jobs:kind==='ORDER_CORRECTION'||kind==='REFUND'&&source==='ONLINE'?data?.targets.orders:data?.targets.sales;
 function optionText(r){return r.part_no?`${r.part_no} · ${r.batch_no||r.name} · ${r.available_qty!=null?'available '+r.available_qty:'KSh '+r.price_kes}`:r.sale_no||r.order_no||`${r.job_no} · ${r.registration}`;}
 function input(k,title,type='text'){return <label>{title}<input type={type} min="0" step={type==='number'?'1':undefined} maxLength={200} required value={payload[k]??''} onChange={e=>changePayload(k,e.target.value)}/></label>;}
 return <Layout title="Requests & approvals | Shilatech" noindex><section className="counterShell"><h1>Requests &amp; approvals</h1><p>Staff request → General manager review → Main administrator applies. General manager requests go directly to the administrator.</p><p className="staffHint">Normal sales and receiving continue immediately. Refund approval does not send money or restock parts. A stock adjustment is a separate request after a physical check.</p>{error&&<p className="staffError" role="alert">{error}</p>}{message&&<p className="staffSuccess" role="status">{message}</p>}{!data?<p>Loading requests…</p>:<>
 {!!data.kinds.length&&<details className="staffRecord" open><summary><strong>Submit an exception request</strong></summary><form className="staffForm" onSubmit={e=>{e.preventDefault();key.current||=crypto.randomUUID();send({action:'CREATE',requestKey:key.current,kind,targetId,reason,payload:kind==='REFUND'?{...payload,source}:payload});}}><fieldset disabled={busy} className="staffReadOnlyContent"><div className="staffGrid"><label>Request type<select value={kind} onChange={e=>{setKind(e.target.value);setTarget('');setPayload({});key.current=null;}}>{data.kinds.map(k=><option key={k}>{k}</option>)}</select></label>
 {kind==='REFUND'&&<label>Sale type<select value={source} onChange={e=>{changePayload('source',e.target.value);setTarget('');}}><option>POS</option>{data.user.role!=='cashier'&&<option>ONLINE</option>}</select></label>}
 <label>{kind==='STOCK_ADJUSTMENT'?'Batch to adjust':'Record'}<select required value={targetId} onChange={e=>{setTarget(e.target.value);key.current=null;}}><option value="">Choose a record</option>{(list||[]).map(r=><option key={r.id} value={r.id}>#{r.id} · {optionText(r)}</option>)}</select></label>
 {kind==='PRICE_CHANGE'&&input('priceKes','New catalogue price (whole KSh)','number')}{kind==='STOCK_ADJUSTMENT'&&input('quantity','Physically counted available quantity in this batch','number')}{kind==='REFUND'&&input('amountKes','Refund amount (whole KSh)','number')}
 {['SALE_CORRECTION','GARAGE_CORRECTION'].includes(kind)&&<><label>Field<select required value={payload.field||''} onChange={e=>changePayload('field',e.target.value)}><option value="">Choose field</option>{(kind==='SALE_CORRECTION'?['customer_name','payment_reference']:['customer_name','phone','vehicle','registration','service','status']).map(f=><option key={f}>{f}</option>)}</select></label>{input('value','Corrected value')}</>}
 {kind==='ORDER_CORRECTION'&&<><label>Order status<select value={payload.status||''} onChange={e=>changePayload('status',e.target.value)}><option value="">No change</option>{['Pending','Processing','Shipped','Out for Delivery','Delivered','Cancelled'].map(s=><option key={s}>{s}</option>)}</select></label><label>Payment record status<select value={payload.paymentStatus||''} onChange={e=>changePayload('paymentStatus',e.target.value)}><option value="">No change</option>{['Pending','Paid','Completed','Failed'].map(s=><option key={s}>{s}</option>)}</select></label></>}
 </div><label>Reason and supporting reference<textarea required maxLength={1000} value={reason} onChange={e=>{setReason(e.target.value);key.current=null;}}/></label><p className="staffHint">Explain the original error and the exact correction. Garage status values: BOOKED, INSPECTION, AWAITING_CUSTOMER, IN_PROGRESS, READY, COMPLETED, CANCELLED. Financial sale amounts are corrected through an approved refund and, if needed, a new correctly priced sale.</p><button className="button primary" disabled={busy}>Submit for approval</button></fieldset></form></details>}
 <h2>Request history</h2>{!data.requests.length&&<p>No requests yet.</p>}{data.requests.map(r=>{const canReview=String(r.requested_by)!==String(data.user.id)&&String(r.reviewed_by)!==String(data.user.id)&&(data.user.role==='general_manager'&&r.status==='PENDING_MANAGER'||data.user.role==='admin'&&r.status==='PENDING_ADMIN');return <article key={r.id} className="staffRecord"><h3>#{r.id} · {label(r.kind)} · record #{r.target_id}</h3><span className="staffTag">{label(r.status)}</span><p>{r.reason}</p><p className="staffHint">Requested by {r.requester_name} · {new Date(r.created_at).toLocaleString('en-KE')}{r.reviewer_name&&` · Reviewed by ${r.reviewer_name}`}{r.approver_name&&` · Applied by ${r.approver_name}`}</p><div className="staffGrid"><div><strong>Original values</strong><pre>{JSON.stringify(r.before_values,null,2)}</pre></div><div><strong>Requested change</strong><pre>{JSON.stringify(r.payload,null,2)}</pre></div></div>{r.review_note&&<p>Review: {r.review_note}</p>}{canReview&&<><label className="staffForm">Decision note<textarea maxLength={1000} value={review[r.id]||''} onChange={e=>setReview({...review,[r.id]:e.target.value})}/></label><div className="staffActions"><button className="button primary" disabled={busy||!review[r.id]?.trim()} onClick={()=>send({action:'APPROVE',id:r.id,note:review[r.id]})}>{data.user.role==='admin'?'Approve and apply':'Recommend to administrator'}</button><button disabled={busy||!review[r.id]?.trim()} onClick={()=>send({action:'REJECT',id:r.id,note:review[r.id]})}>Reject</button></div></>}</article>;})}
 <h2>Approved refunds</h2><p>Amounts below are approved credits. Pay the customer outside this website, then the administrator records the actual payout reference. Do not pay twice.</p>{data.refunds.map(f=><article className="staffRecord" key={f.id}><h3>{f.sale_no||f.order_no} · KSh {Number(f.amount_kes).toLocaleString()}</h3><span className="staffTag">{label(f.status)}</span>{f.payout_reference&&<p>Recorded payout: {f.payout_reference}</p>}{f.status==='AWAITING_PAYOUT'&&data.user.role==='admin'&&<form className="staffForm" onSubmit={e=>{e.preventDefault();const values=new FormData(e.currentTarget);if(window.confirm('Confirm this refund has already been paid outside the website. This records it only.'))send({action:'RECORD_PAYOUT',id:f.id,reference:values.get('reference')});}}><label>Actual transfer reference / cash voucher<input name="reference" required maxLength={100}/></label><button disabled={busy}>Record completed external payout</button></form>}</article>)}
 </>}</section></Layout>;
}
