import { useEffect, useRef, useState } from 'react';
import Layout from '../components/Layout';

const deliveryRoles=new Set(['admin','warehouse_manager','dispatch','delivery_driver']);

export default function Delivery(){
  const [auth,setAuth]=useState('checking');
  const [login,setLogin]=useState({email:'',password:''});
  const [jobs,setJobs]=useState([]); const [error,setError]=useState(''); const [busy,setBusy]=useState(false); const [active,setActive]=useState(null); const [success,setSuccess]=useState('');
  const [proof,setProof]=useState({recipientName:'',notes:''});
  const canvasRef=useRef(null); const drawing=useRef(false); const signed=useRef(false);

  async function load(){setError('');try{const r=await fetch('/api/delivery/overview');const j=await r.json();if(r.status===401||r.status===403){setAuth('login');setJobs([]);return;}if(!r.ok)throw new Error(j.error||'Could not load deliveries.');setJobs(j.jobs||[]);setAuth('staff');}catch(e){setError(e.message);}}
  useEffect(()=>{(async()=>{try{const r=await fetch('/api/auth/me');const j=await r.json();if(r.ok&&deliveryRoles.has(j.user?.role)){setAuth('staff');await load();}else setAuth('login');}catch{setAuth('login');}})();},[]);

  async function signIn(e){e.preventDefault();setBusy(true);setError('');try{const r=await fetch('/api/auth/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(login)});const j=await r.json();if(!r.ok)throw new Error(j.error||'Sign in failed.');if(!deliveryRoles.has(j.user?.role)){await fetch('/api/auth/logout',{method:'POST'});throw new Error('This account is not authorized for deliveries.');}setLogin({email:'',password:''});setAuth('staff');await load();}catch(e2){setError(e2.message);}finally{setBusy(false);}}
  async function logout(){await fetch('/api/auth/logout',{method:'POST'});setJobs([]);setAuth('login');setActive(null);}

  function canvasPoint(e){const c=canvasRef.current;const rect=c.getBoundingClientRect();const p=e.touches?.[0]||e;return {x:(p.clientX-rect.left)*(c.width/rect.width),y:(p.clientY-rect.top)*(c.height/rect.height)};}
  function startDraw(e){e.preventDefault();const c=canvasRef.current;if(!c)return;drawing.current=true;const p=canvasPoint(e);const ctx=c.getContext('2d');ctx.beginPath();ctx.moveTo(p.x,p.y);}
  function moveDraw(e){if(!drawing.current)return;e.preventDefault();const c=canvasRef.current;const p=canvasPoint(e);const ctx=c.getContext('2d');ctx.lineWidth=3;ctx.lineCap='round';ctx.strokeStyle='#111';ctx.lineTo(p.x,p.y);ctx.stroke();signed.current=true;}
  function endDraw(){drawing.current=false;}
  function clearSignature(){const c=canvasRef.current;if(c){c.getContext('2d').clearRect(0,0,c.width,c.height);}signed.current=false;}
  function openProof(job){setActive(job);setProof({recipientName:job.customer_name||'',notes:''});setSuccess('');setTimeout(clearSignature,0);}

  function getLocation(){return new Promise(resolve=>{if(!navigator.geolocation)return resolve({lat:null,lng:null});navigator.geolocation.getCurrentPosition(p=>resolve({lat:p.coords.latitude,lng:p.coords.longitude}),()=>resolve({lat:null,lng:null}),{enableHighAccuracy:true,timeout:7000,maximumAge:30000});});}
  async function submitProof(e){e.preventDefault();if(!active)return;if(!signed.current){setError('Customer signature is required.');return;}setBusy(true);setError('');try{const loc=await getLocation();const signatureData=canvasRef.current.toDataURL('image/png');const r=await fetch('/api/delivery/complete',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({deliveryId:active.id,recipientName:proof.recipientName,notes:proof.notes,signatureData,...loc})});const j=await r.json();if(!r.ok)throw new Error(j.error||'Could not complete delivery.');setSuccess(`Order ${active.order_no} marked as Delivered.`);setActive(null);clearSignature();await load();}catch(e2){setError(e2.message);}finally{setBusy(false);}}

  if(auth==='checking') return <Layout><div className="deliveryLogin"><div className="deliveryLoginCard"><p>Loading secure delivery portal…</p></div></div></Layout>;
  if(auth==='login') return <Layout><div className="deliveryLogin"><form className="deliveryLoginCard" onSubmit={signIn}><span className="eyebrow">SHILATECH PDA</span><h1>Delivery Staff Login</h1><p>Secure mobile access for authorized drivers and dispatch staff.</p>{error&&<div className="deliveryAlert">{error}</div>}<label>Email<input required type="email" autoComplete="username" value={login.email} onChange={e=>setLogin({...login,email:e.target.value})}/></label><label>Password<input required type="password" autoComplete="current-password" value={login.password} onChange={e=>setLogin({...login,password:e.target.value})}/></label><button disabled={busy} className="button greenPrimary">{busy?'Signing in…':'Sign in to deliveries'}</button></form></div></Layout>;

  return <div className="deliveryPage"><header className="deliveryHeader"><div className="deliveryShell deliveryBrand"><div className="deliveryBrandMark"><div className="deliveryBrandIcon">S</div><div className="deliveryBrandText"><b>SHILATECH</b><span>PDA DELIVERY SYSTEM</span></div></div><button className="deliveryLogout" onClick={logout}>Sign out</button></div></header><main className="deliveryShell"><section className="deliveryHero"><span>LIVE DELIVERY OPERATIONS</span><h1>Driver Delivery Queue</h1><p>Open a delivery, confirm the customer, capture their signature and submit proof of delivery. The customer order updates automatically.</p></section>{error&&<div className="deliveryAlert">{error}</div>}{success&&<div className="deliverySuccess">{success}</div>}{!jobs.length?<div className="deliveryEmpty">No deliveries are currently waiting.</div>:jobs.map(job=><article className="deliveryCard" key={job.id}><div className="deliveryTop"><div><b>{job.order_no}</b><span>{job.job_no}</span></div><div className="deliveryStatus">{job.status}</div></div><div className="deliveryCustomer"><b>{job.customer_name}</b><span>{job.phone}</span><span>{job.delivery_address} · {job.delivery_zone}</span></div><div className="deliveryItems">{(job.items||[]).map((i,idx)=><div className="deliveryItem" key={`${i.partNo}-${idx}`}><div><b>{i.brand} · {i.partNo}</b><span>{i.name}</span></div><strong>×{i.quantity}</strong></div>)}</div><div className="deliveryActions"><a className="deliverySecondary" href={`tel:${job.phone}`}>Call customer</a><a className="deliverySecondary" target="_blank" rel="noreferrer" href={`https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(job.delivery_address)}`}>Open address</a><button className="deliveryPrimary" onClick={()=>openProof(job)}>Capture signature & deliver</button></div>{active?.id===job.id&&<form className="proofPanel" onSubmit={submitProof}><label>Recipient name<input required value={proof.recipientName} onChange={e=>setProof({...proof,recipientName:e.target.value})}/></label><label>Customer signature<div className="signatureBox"><canvas ref={canvasRef} width="700" height="240" onMouseDown={startDraw} onMouseMove={moveDraw} onMouseUp={endDraw} onMouseLeave={endDraw} onTouchStart={startDraw} onTouchMove={moveDraw} onTouchEnd={endDraw}/></div></label><div className="signatureTools"><small>Sign inside the white box</small><button type="button" onClick={clearSignature}>Clear signature</button></div><label>Delivery notes<textarea rows="3" placeholder="Optional notes" value={proof.notes} onChange={e=>setProof({...proof,notes:e.target.value})}/></label><button disabled={busy} className="proofSubmit">{busy?'Saving proof…':'Customer signed — mark Delivered'}</button></form>}</article>)}</main></div>;
}
