import { useEffect, useRef, useState } from 'react';
import Layout from '../components/Layout';

const deliveryRoles=new Set(['admin','warehouse_manager','dispatch','delivery_driver']);
const managementRoles=new Set(['admin','warehouse_manager','dispatch']);
const paid=j=>String(j?.payment_status||'').toLowerCase()==='paid';
const needsMpesa=j=>String(j?.payment_method||'').toLowerCase()==='m-pesa'&&!paid(j);

export default function Delivery(){
  const [auth,setAuth]=useState('checking'); const [user,setUser]=useState(null);
  const [login,setLogin]=useState({email:'',password:''});
  const [jobs,setJobs]=useState([]); const [management,setManagement]=useState({drivers:[],jobs:[]});
  const [newDriver,setNewDriver]=useState({name:'',email:'',phone:'',password:''});
  const [assignments,setAssignments]=useState({});
  const [error,setError]=useState(''); const [busy,setBusy]=useState(false); const [active,setActive]=useState(null); const [success,setSuccess]=useState('');
  const [proof,setProof]=useState({recipientName:'',notes:''});
  const canvasRef=useRef(null); const drawing=useRef(false); const signed=useRef(false);

  async function load(){setError('');try{const r=await fetch('/api/delivery/overview');const j=await r.json();if(r.status===401||r.status===403){setAuth('login');setJobs([]);return;}if(!r.ok)throw new Error(j.error||'Could not load deliveries.');setJobs(j.jobs||[]);setUser(j.user||user);setAuth('staff');if(managementRoles.has(j.user?.role||user?.role))await loadManagement();}catch(e){setError(e.message);}}
  async function loadManagement(){try{const r=await fetch('/api/delivery/manage');const j=await r.json();if(r.ok){setManagement(j);const a={};(j.jobs||[]).forEach(x=>a[x.id]=x.driver_id?String(x.driver_id):'');setAssignments(a);}}catch{}}
  useEffect(()=>{(async()=>{try{const r=await fetch('/api/auth/me');const j=await r.json();if(r.ok&&deliveryRoles.has(j.user?.role)){setUser(j.user);setAuth('staff');await load();}else setAuth('login');}catch{setAuth('login');}})();},[]);

  async function signIn(e){e.preventDefault();setBusy(true);setError('');try{const r=await fetch('/api/auth/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(login)});const j=await r.json();if(!r.ok)throw new Error(j.error||'Sign in failed.');if(!deliveryRoles.has(j.user?.role)){await fetch('/api/auth/logout',{method:'POST'});throw new Error('This account is not authorized for deliveries.');}setUser(j.user);setLogin({email:'',password:''});setAuth('staff');await load();}catch(e2){setError(e2.message);}finally{setBusy(false);}}
  async function logout(){await fetch('/api/auth/logout',{method:'POST'});setJobs([]);setManagement({drivers:[],jobs:[]});setAuth('login');setActive(null);setUser(null);}

  async function managementAction(body){setBusy(true);setError('');setSuccess('');try{const r=await fetch('/api/delivery/manage',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const j=await r.json();if(!r.ok)throw new Error(j.error||'Action failed.');setSuccess(body.action==='CREATE_DRIVER'?'Driver account saved.':'Delivery assignment updated.');await load();}catch(e){setError(e.message);}finally{setBusy(false);}}
  async function createDriver(e){e.preventDefault();await managementAction({action:'CREATE_DRIVER',...newDriver});setNewDriver({name:'',email:'',phone:'',password:''});}
  async function assignDriver(deliveryId){const driverId=assignments[deliveryId];await managementAction({action:driverId?'ASSIGN_DRIVER':'UNASSIGN_DRIVER',deliveryId,driverId:driverId?Number(driverId):null});}
  async function promptPayment(job){if(paid(job))return;setBusy(true);setError('');setSuccess('');try{const r=await fetch('/api/payments/mpesa/stk',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({deliveryId:job.id,phone:job.phone})});const j=await r.json();if(!r.ok)throw new Error(j.error||'Could not send payment prompt.');setSuccess(`M-Pesa prompt sent to ${job.phone}. Ask the customer to complete payment, then tap Refresh payment status.`);}catch(e){setError(e.message);}finally{setBusy(false);}}

  function canvasPoint(e){const c=canvasRef.current;const rect=c.getBoundingClientRect();const p=e.touches?.[0]||e;return {x:(p.clientX-rect.left)*(c.width/rect.width),y:(p.clientY-rect.top)*(c.height/rect.height)};}
  function startDraw(e){e.preventDefault();const c=canvasRef.current;if(!c)return;drawing.current=true;const p=canvasPoint(e);const ctx=c.getContext('2d');ctx.beginPath();ctx.moveTo(p.x,p.y);}
  function moveDraw(e){if(!drawing.current)return;e.preventDefault();const c=canvasRef.current;const p=canvasPoint(e);const ctx=c.getContext('2d');ctx.lineWidth=3;ctx.lineCap='round';ctx.strokeStyle='#111';ctx.lineTo(p.x,p.y);ctx.stroke();signed.current=true;}
  function endDraw(){drawing.current=false;}
  function clearSignature(){const c=canvasRef.current;if(c)c.getContext('2d').clearRect(0,0,c.width,c.height);signed.current=false;}
  function openProof(job){if(needsMpesa(job)){setError('Payment is still pending. Prompt the customer for M-Pesa payment first.');return;}setActive(job);setProof({recipientName:job.customer_name||'',notes:''});setSuccess('');setTimeout(clearSignature,0);}
  function getLocation(){return new Promise(resolve=>{if(!navigator.geolocation)return resolve({lat:null,lng:null});navigator.geolocation.getCurrentPosition(p=>resolve({lat:p.coords.latitude,lng:p.coords.longitude}),()=>resolve({lat:null,lng:null}),{enableHighAccuracy:true,timeout:7000,maximumAge:30000});});}
  async function submitProof(e){e.preventDefault();if(!active)return;if(!signed.current){setError('Customer signature is required.');return;}setBusy(true);setError('');try{const loc=await getLocation();const signatureData=canvasRef.current.toDataURL('image/png');const r=await fetch('/api/delivery/complete',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({deliveryId:active.id,recipientName:proof.recipientName,notes:proof.notes,signatureData,...loc})});const j=await r.json();if(!r.ok)throw new Error(j.error||'Could not complete delivery.');setSuccess(`Order ${active.order_no} marked as Delivered.`);setActive(null);clearSignature();await load();}catch(e2){setError(e2.message);}finally{setBusy(false);}}

  if(auth==='checking') return <Layout><div className="deliveryLogin"><div className="deliveryLoginCard"><p>Loading secure delivery portal…</p></div></div></Layout>;
  if(auth==='login') return <Layout><div className="deliveryLogin"><form className="deliveryLoginCard" onSubmit={signIn}><span className="eyebrow">SHILATECH PDA</span><h1>Delivery Staff Login</h1><p>Secure mobile access for authorized drivers and dispatch staff.</p>{error&&<div className="deliveryAlert">{error}</div>}<label>Email<input required type="email" autoComplete="username" value={login.email} onChange={e=>setLogin({...login,email:e.target.value})}/></label><label>Password<input required type="password" autoComplete="current-password" value={login.password} onChange={e=>setLogin({...login,password:e.target.value})}/></label><button disabled={busy} className="button greenPrimary">{busy?'Signing in…':'Sign in to deliveries'}</button></form></div></Layout>;

  const canManage=managementRoles.has(user?.role);
  return <div className="deliveryPage"><header className="deliveryHeader"><div className="deliveryShell deliveryBrand"><div className="deliveryBrandMark"><img className="deliverySiteLogo" src="/shilatech-logo-small.webp" alt="Shilatech Auto Spares"/><div className="deliveryBrandText"><span>PDA DELIVERY SYSTEM</span></div></div><button className="deliveryLogout" onClick={logout}>Sign out</button></div></header><main className="deliveryShell">
    <section className="deliveryHero"><span>LIVE DELIVERY OPERATIONS</span><h1>{canManage?'Delivery Control Centre':'My Assigned Deliveries'}</h1><p>{canManage?'Create driver accounts, assign dispatched orders and monitor payment plus proof-of-delivery completion.':'Only deliveries assigned to your driver account appear here. Confirm payment, then capture the customer signature to complete delivery.'}</p></section>
    {error&&<div className="deliveryAlert">{error}</div>}{success&&<div className="deliverySuccess">{success}</div>}
    {canManage&&<section className="deliveryManagement"><div className="deliveryManagerPanel"><h2>Driver accounts</h2><p>Create a secure PDA login for each Shilatech delivery driver.</p>{user?.role!=='dispatch'?<form onSubmit={createDriver} className="driverCreateForm"><input required placeholder="Driver name" value={newDriver.name} onChange={e=>setNewDriver({...newDriver,name:e.target.value})}/><input required type="email" placeholder="Driver email" value={newDriver.email} onChange={e=>setNewDriver({...newDriver,email:e.target.value})}/><input placeholder="Phone" value={newDriver.phone} onChange={e=>setNewDriver({...newDriver,phone:e.target.value})}/><input required minLength="8" type="password" placeholder="Temporary password" value={newDriver.password} onChange={e=>setNewDriver({...newDriver,password:e.target.value})}/><button disabled={busy}>Save driver</button></form>:<p className="deliveryHint">Dispatch can assign drivers; administrator/warehouse manager creates driver accounts.</p>}<div className="driverList">{management.drivers.length?management.drivers.map(d=><div key={d.id}><b>{d.name}</b><span>{d.email}{d.phone?` · ${d.phone}`:''}</span></div>):<span>No driver accounts yet.</span>}</div></div><div className="deliveryManagerPanel"><h2>Assign deliveries</h2><p>Choose the driver who should receive each job on their PDA.</p>{management.jobs.length?management.jobs.map(j=><div className="assignmentRow" key={j.id}><div><b>{j.order_no}</b><span>{j.customer_name} · {j.delivery_zone}</span></div><select value={assignments[j.id]||''} onChange={e=>setAssignments({...assignments,[j.id]:e.target.value})}><option value="">Unassigned</option>{management.drivers.map(d=><option key={d.id} value={d.id}>{d.name}</option>)}</select><button disabled={busy} onClick={()=>assignDriver(j.id)}>Apply</button></div>):<div className="deliveryHint">No active delivery jobs.</div>}</div></section>}
    <section className="deliveryQueueTitle"><h2>{canManage?'Active delivery queue':'My delivery queue'}</h2><span>{jobs.length} job{jobs.length===1?'':'s'}</span></section>
    {!jobs.length?<div className="deliveryEmpty">{canManage?'No deliveries are currently waiting.':'No deliveries are currently assigned to you.'}</div>:jobs.map(job=><article className="deliveryCard" key={job.id}><div className="deliveryTop"><div><b>{job.order_no}</b><span>{job.job_no}</span></div><div className="deliveryStatus">{job.status}</div></div><div className="deliveryCustomer"><b>{job.customer_name}</b><span>{job.phone}</span><span>{job.delivery_address} · {job.delivery_zone}</span>{canManage&&<span>Driver: {job.driver_name||'Unassigned'}</span>}</div><div className={`deliveryPayment ${paid(job)?'isPaid':'isPending'}`}><div><b>Payment: {paid(job)?'PAID':'PENDING'}</b><span>{job.payment_method} · KSh {Number(job.total_kes||0).toLocaleString()}</span></div>{needsMpesa(job)?<div className="deliveryPaymentActions"><button disabled={busy} onClick={()=>promptPayment(job)}>Prompt Customer to Pay</button><button disabled={busy} onClick={load}>Refresh payment status</button></div>:<strong>{paid(job)?'✓ Payment confirmed':'Payment handled outside M-Pesa'}</strong>}</div><div className="deliveryItems">{(job.items||[]).map((i,idx)=><div className="deliveryItem" key={`${i.partNo}-${idx}`}><div><b>{i.brand} · {i.partNo}</b><span>{i.name}</span></div><strong>×{i.quantity}</strong></div>)}</div><div className="deliveryActions"><a className="deliverySecondary" href={`tel:${job.phone}`}>Call customer</a><a className="deliverySecondary" target="_blank" rel="noreferrer" href={`https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(job.delivery_address)}`}>Open address</a><button className="deliveryPrimary" disabled={(!job.driver_id&&canManage)||needsMpesa(job)} onClick={()=>openProof(job)}>{needsMpesa(job)?'Payment required before delivery':'Capture signature & deliver'}</button></div>{active?.id===job.id&&<form className="proofPanel" onSubmit={submitProof}><label>Recipient name<input required value={proof.recipientName} onChange={e=>setProof({...proof,recipientName:e.target.value})}/></label><label>Customer signature<div className="signatureBox"><canvas ref={canvasRef} width="700" height="240" onMouseDown={startDraw} onMouseMove={moveDraw} onMouseUp={endDraw} onMouseLeave={endDraw} onTouchStart={startDraw} onTouchMove={moveDraw} onTouchEnd={endDraw}/></div></label><div className="signatureTools"><small>Sign inside the white box</small><button type="button" onClick={clearSignature}>Clear signature</button></div><label>Delivery notes<textarea rows="3" placeholder="Optional notes" value={proof.notes} onChange={e=>setProof({...proof,notes:e.target.value})}/></label><button disabled={busy} className="proofSubmit">{busy?'Saving proof…':'Customer signed — mark Delivered'}</button></form>}</article>)}
  </main></div>;
}
