import { useEffect,useState } from 'react';
import Layout from '../components/Layout';
export default function MyHR(){
 const [data,setData]=useState(null),[error,setError]=useState(''),[form,setForm]=useState({startDate:'',endDate:'',leaveType:'Annual',reason:''});
 async function load(){const r=await fetch('/api/hr');const j=await r.json();if(!r.ok)throw Error(j.error);setData(j)}
 useEffect(()=>{load().catch(e=>setError(e.message))},[]);
 async function submit(e){e.preventDefault();const r=await fetch('/api/hr',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'LEAVE',...form})});const j=await r.json();if(!r.ok)throw Error(j.error);setForm({startDate:'',endDate:'',leaveType:'Annual',reason:''});await load()}
 return <Layout title="My HR | Shilatech staff" noindex><section className="counterShell hrPage"><span className="staffEyebrow">SHILATECH · MY HR</span><h1>My HR</h1><p>Apply for leave and view your own approved payslips.</p>{error&&<p role="alert">{error}</p>}<form onSubmit={e=>submit(e).catch(x=>setError(x.message))}><h2>Leave application</h2><label>Start date<input required type="date" value={form.startDate} onChange={e=>setForm({...form,startDate:e.target.value})}/></label><label>End date<input required type="date" value={form.endDate} onChange={e=>setForm({...form,endDate:e.target.value})}/></label><label>Leave type<select value={form.leaveType} onChange={e=>setForm({...form,leaveType:e.target.value})}><option>Annual</option><option>Sick</option><option>Unpaid</option></select></label><label>Reason<textarea required maxLength={1000} value={form.reason} onChange={e=>setForm({...form,reason:e.target.value})}/></label><button>Submit leave application</button></form><h2>My approved payslips</h2>{!data?.payslips?.length?<p>No approved payslips yet.</p>:data.payslips.map(p=><article key={p.id}><strong>{p.period}</strong><p>Approved · Net KSh {Number(p.amounts.net).toLocaleString('en-KE',{minimumFractionDigits:2})}</p><button type="button" onClick={()=>window.print()}>Print payslip</button></article>)}<h2>Test email</h2><p>Email inboxes are not connected. This tab is a placeholder until the company domain has an email provider.</p><style jsx>{`.hrPage{color:#e7ede4;background:#080c08;min-height:65vh;line-height:1.7}.hrPage h1,.hrPage h2{color:#70c342}.hrPage form,.hrPage article{display:grid;gap:12px;max-width:680px;padding:20px;border:1px solid #405338;margin:18px 0}.hrPage input,.hrPage select,.hrPage textarea{display:block;width:100%;box-sizing:border-box;padding:10px;background:#101910;color:#fff;border:1px solid #53654b}.hrPage button{padding:10px;background:#65bd35;border:0}`}</style></section></Layout>
}

