import {useEffect,useState} from 'react';
import Layout from '../components/Layout';
const blank={startDate:'',endDate:'',leaveType:'Annual',reason:''};
export default function MyHR(){
 const [data,setData]=useState(null),[error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false),[form,setForm]=useState(blank),[notes,setNotes]=useState({}),[selected,setSelected]=useState(null);
 async function load(){const r=await fetch('/api/hr',{cache:'no-store'});const j=await r.json();if(!r.ok)throw Error(j.error);setData(j);}
 useEffect(()=>{load().catch(e=>setError(e.message));},[]);
 async function send(body){setBusy(true);setError('');setNotice('');try{const r=await fetch('/api/hr',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const j=await r.json();if(!r.ok)throw Error(j.error);await load();setNotice('Saved successfully.');if(body.action==='LEAVE')setForm(blank);}catch(e){setError(e.message);}finally{setBusy(false);}}
 const payslip=data?.payslips.find(p=>String(p.id)===String(selected));
 const managing=['admin','hr','general_manager'].includes(data?.role);
 const amounts={basic:'Basic pay',allowances:'Allowances',gross:'Gross pay',nssf:'Employee NSSF',shif:'SHIF',housing:'Housing levy',taxable:'Taxable pay',relief:'Personal relief',paye:'PAYE',net:'Net salary',employerNssf:'Employer NSSF',employerHousing:'Employer housing levy'};
 return <Layout title="My HR | Shilatech staff" noindex><section className="counterShell hrPage">
  <div className="noPrint"><span className="staffEyebrow">SHILATECH · STAFF SERVICES</span><h1>{data?.role==='hr'?'HR administration':'My HR'}</h1>
  <p>Leave requests and your own approved payslips. HR review does not approve leave; final approval remains with the administrator.</p>
  <nav aria-label="HR sections"><a href="#leave">Leave applications</a> · <a href="#payslips">My payslips</a> · <a href="#email">Email</a>{data?.staff.length>0&&<> · <a href="#directory">Staff directory</a></>}</nav>
  {error&&<p role="alert">{error}</p>}{notice&&<p role="status">{notice}</p>}
  {!data&&<p>Loading staff services…</p>}
  {data&&!data.ready&&<article><h2>Initialise HR records</h2><p>This creates empty leave and audit tables. It does not create leave requests or change stock, salaries or sales.</p>{data.role==='admin'?<button disabled={busy} onClick={()=>send({action:'SETUP'})}>Initialise HR records</button>:<p>Ask the administrator to initialise HR records.</p>}</article>}
  {data?.ready&&<><form id="leave" onSubmit={e=>{e.preventDefault();send({action:'LEAVE',...form});}}><h2>Apply for leave</h2><label>Start date<input required type="date" value={form.startDate} onChange={e=>setForm({...form,startDate:e.target.value})}/></label><label>End date<input required type="date" min={form.startDate} value={form.endDate} onChange={e=>setForm({...form,endDate:e.target.value})}/></label><label>Leave type<select value={form.leaveType} onChange={e=>setForm({...form,leaveType:e.target.value})}><option>Annual</option><option>Sick</option><option>Unpaid</option></select></label><label>Reason<textarea required maxLength={1000} value={form.reason} onChange={e=>setForm({...form,reason:e.target.value})}/></label><button disabled={busy}>Submit leave application</button></form>
  <h2>{managing?'Leave review':'My leave requests'}</h2>{!data.leaves.length&&<p>No leave requests yet.</p>}{data.leaves.map(l=>{const own=String(l.employee_id)===String(data.userId);const stage=data.role==='general_manager'&&l.status==='PENDING_MANAGER'||data.role==='admin'&&l.status==='PENDING_ADMIN';const hr=data.role==='hr'&&['PENDING_MANAGER','PENDING_ADMIN'].includes(l.status);return <article key={l.id}><h3>{l.employee_name} · {l.leave_type}</h3><p>{String(l.start_date).slice(0,10)} to {String(l.end_date).slice(0,10)} · {l.status.replaceAll('_',' ')}</p><p>{l.reason}</p>{!own&&(stage||hr)&&<><label>Review note<textarea maxLength={1000} value={notes[l.id]||''} onChange={e=>setNotes({...notes,[l.id]:e.target.value})}/></label><button disabled={busy||!notes[l.id]?.trim()} onClick={()=>send({action:'DECIDE',id:l.id,decision:hr?'NOTE':'APPROVE',note:notes[l.id]})}>{hr?'Save HR review note':data.role==='general_manager'?'Recommend to administrator':'Approve leave'}</button>{!hr&&<button disabled={busy||!notes[l.id]?.trim()} onClick={()=>send({action:'DECIDE',id:l.id,decision:'REJECT',note:notes[l.id]})}>Reject leave</button>}</>}{data.events.filter(e=>String(e.leave_id)===String(l.id)).map(e=><p key={e.id}><small>{e.actor_name} · {e.action} · {e.note}</small></p>)}</article>;})}</>}
  <h2 id="payslips">My approved payslips</h2><p>Only payslips belonging to your account are shown.</p>{!data?.payslips.length?<p>No approved payslips yet.</p>:data.payslips.map(p=><button key={p.id} onClick={()=>setSelected(p.id)}>View payslip {p.period}</button>)}
  {data?.staff.length>0&&<><h2 id="directory">Staff directory</h2><p>Account creation, password resets and role changes remain administrator-only. Private document uploads are not available yet.</p>{data.staff.map(s=><p key={s.id}>{s.name} · {s.email} · {s.role.replaceAll('_',' ')}</p>)}</>}
  <h2 id="email">Email</h2><p>Test placeholder only. No mailbox or external email delivery is connected.</p></div>
  {payslip&&<><article id="personal-payslip"><img src="/shilatech-logo.webp" width="100" height="64" alt="Shilatech Auto Spares"/><h2>Shilatech payslip</h2><p>{payslip.employee_name} · {payslip.period} · Record {payslip.id}</p><p>APPROVED — PAYMENT NOT SENT</p><dl>{Object.entries(amounts).map(([k,label])=><div key={k}><dt>{label}</dt><dd>KSh {Number(payslip.amounts[k]).toLocaleString('en-KE',{minimumFractionDigits:2,maximumFractionDigits:2})}</dd></div>)}</dl><p>Salary calculations only; not proof of payment or statutory remittance.</p></article><button className="noPrint" onClick={async()=>{try{await document.querySelector('#personal-payslip img').decode();await document.fonts.ready;window.print();}catch{setError('Please reload: the payslip logo could not load.');}}}>Print / Save payslip as PDF (A5)</button></>}
  <style jsx>{`.hrPage{color:#e7ede4;background:#080c08;min-height:65vh;line-height:1.7}.hrPage h1,.hrPage h2,.hrPage h3,.hrPage a{color:#70c342}form,article{max-width:760px;border:1px solid #405338;padding:20px;margin:20px 0}label{display:block;margin:12px 0}input,select,textarea{display:block;width:100%;box-sizing:border-box;padding:10px;background:#101910;color:white;border:1px solid #53654b}button{padding:12px;background:#65bd35;color:#071003;border:0;margin:6px;cursor:pointer}button:disabled{opacity:.5;cursor:not-allowed}dl>div{display:flex;justify-content:space-between;border-bottom:1px solid #405338;gap:20px}dd{margin:0}#personal-payslip img{object-fit:contain}`}</style>
  <style jsx global>{`@page{size:A5 portrait;margin:10mm}@media print{body *{visibility:hidden}body:has(#personal-payslip) *:not(:has(#personal-payslip)):not(#personal-payslip):not(#personal-payslip *){display:none!important}body *:has(#personal-payslip){margin:0!important;padding:0!important;min-height:0!important;border:0!important}#personal-payslip,#personal-payslip *{visibility:visible;color:black!important;background:white!important}#personal-payslip{margin:0!important;padding:0!important;width:128mm!important;border:0!important;font-size:9pt;line-height:1.4}#personal-payslip h2{font-size:15pt}#personal-payslip p{margin:2mm 0}#personal-payslip dd{white-space:nowrap}.noPrint{display:none!important}}`}</style>
 </section></Layout>;
}
