import { useEffect,useState } from 'react';
import Layout from '../components/Layout';

const supplierBlank={name:'',contactName:'',phone:'',email:'',address:''};
const staffBlank={name:'',email:'',phone:'',role:'warehouse_clerk',password:''};
const poBlank={supplierId:'',productId:'',quantity:'',unitCost:'',expectedDate:'',notes:''};

export default function Operations(){
 const [data,setData]=useState(null),[staff,setStaff]=useState({staff:[],roles:[]}),[error,setError]=useState(''),[success,setSuccess]=useState(''),[busy,setBusy]=useState(false);
 const [supplier,setSupplier]=useState(supplierBlank),[employee,setEmployee]=useState(staffBlank),[po,setPo]=useState(poBlank);
 async function load(){setError('');try{const [a,b]=await Promise.all([fetch('/api/admin/operations'),fetch('/api/admin/staff')]);const aj=await a.json();const bj=await b.json();if(!a.ok)throw new Error(aj.error||'Could not load operations.');setData(aj);if(b.ok)setStaff(bj);}catch(e){setError(e.message);}}
 useEffect(()=>{load();},[]);
 async function post(url,body,after){setBusy(true);setError('');setSuccess('');try{const r=await fetch(url,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const j=await r.json();if(!r.ok)throw new Error(j.error||'Action failed.');setSuccess('Saved successfully.');if(after)after();await load();}catch(e){setError(e.message);}finally{setBusy(false);}}
 if(!data&&error)return <Layout><section className="section"><div className="container"><div className="panel"><h2>Operations access</h2><p>{error}</p><a className="button primary" href="/staff-login?next=/operations">Sign in</a></div></div></section></Layout>;
 return <Layout><section className="pageHero compactHero"><div className="container"><span className="eyebrow">SHILATECH V1 OPERATIONS</span><h1>Management Operations Centre</h1><p>Suppliers, purchase orders, reorder controls, employee roles and management visibility. Net sales include online and counter sales, less approved refund credits.</p></div></section><section className="section"><div className="container">
 {error&&<div className="panel adminError"><p>{error}</p></div>}{success&&<div className="panel" style={{borderColor:'#58b72a'}}><p>{success}</p></div>}
 {!data?<div className="panel">Loading operations…</div>:<>
 <div className="metrics"><div><span>Products</span><strong>{data.metrics.products}</strong></div><div><span>Units on hand</span><strong>{data.metrics.units}</strong></div><div><span>Orders this month</span><strong>{data.metrics.month_orders}</strong></div><div><span>Net sales this month</span><strong>KSh {Number(data.metrics.month_paid_sales||0).toLocaleString()}</strong></div></div>
 <div className="opsGrid">
  <form className="panel opsCard" onSubmit={e=>{e.preventDefault();post('/api/admin/operations',{action:'CREATE_SUPPLIER',...supplier},()=>setSupplier(supplierBlank));}}><span className="eyebrow">PURCHASING</span><h2>Add supplier</h2><input required placeholder="Supplier/company name" value={supplier.name} onChange={e=>setSupplier({...supplier,name:e.target.value})}/><input placeholder="Contact person" value={supplier.contactName} onChange={e=>setSupplier({...supplier,contactName:e.target.value})}/><input placeholder="Phone" value={supplier.phone} onChange={e=>setSupplier({...supplier,phone:e.target.value})}/><input type="email" placeholder="Email" value={supplier.email} onChange={e=>setSupplier({...supplier,email:e.target.value})}/><textarea rows="3" placeholder="Address" value={supplier.address} onChange={e=>setSupplier({...supplier,address:e.target.value})}/><button className="button primary" disabled={busy}>Save supplier</button></form>
  <form className="panel opsCard" onSubmit={e=>{e.preventDefault();post('/api/admin/operations',{action:'CREATE_PO',supplierId:Number(po.supplierId),expectedDate:po.expectedDate,notes:po.notes,items:[{productId:Number(po.productId),quantity:Number(po.quantity),unitCost:Number(po.unitCost)||null}]},()=>setPo(poBlank));}}><span className="eyebrow">STOCK REPLENISHMENT</span><h2>Create purchase order</h2><select required value={po.supplierId} onChange={e=>setPo({...po,supplierId:e.target.value})}><option value="">Select supplier</option>{data.suppliers.map(s=><option value={s.id} key={s.id}>{s.name}</option>)}</select><select required value={po.productId} onChange={e=>setPo({...po,productId:e.target.value})}><option value="">Select part</option>{data.products.map(p=><option value={p.id} key={p.id}>{p.brand} · {p.part_no} — {p.name}</option>)}</select><div className="opsRow"><input required type="number" min="1" placeholder="Quantity" value={po.quantity} onChange={e=>setPo({...po,quantity:e.target.value})}/><input type="number" min="0" placeholder="Unit cost KSh" value={po.unitCost} onChange={e=>setPo({...po,unitCost:e.target.value})}/></div><input type="date" value={po.expectedDate} onChange={e=>setPo({...po,expectedDate:e.target.value})}/><textarea rows="3" placeholder="Notes" value={po.notes} onChange={e=>setPo({...po,notes:e.target.value})}/><button className="button primary" disabled={busy}>Create PO</button></form>
  <form className="panel opsCard" onSubmit={e=>{e.preventDefault();post('/api/admin/staff',{action:'CREATE',...employee},()=>setEmployee(staffBlank));}}><span className="eyebrow">ACCESS CONTROL</span><h2>Create employee</h2><input required placeholder="Employee name" value={employee.name} onChange={e=>setEmployee({...employee,name:e.target.value})}/><input required type="email" placeholder="Employee email" value={employee.email} onChange={e=>setEmployee({...employee,email:e.target.value})}/><input placeholder="Phone" value={employee.phone} onChange={e=>setEmployee({...employee,phone:e.target.value})}/><select value={employee.role} onChange={e=>setEmployee({...employee,role:e.target.value})}>{(staff.roles||[]).map(r=><option value={r} key={r}>{r.replaceAll('_',' ')}</option>)}</select><input required minLength="8" type="password" placeholder="Temporary password" value={employee.password} onChange={e=>setEmployee({...employee,password:e.target.value})}/><button className="button primary" disabled={busy}>Create employee</button></form>
 </div>
 <div className="panel"><div className="adminHeading"><div><span className="eyebrow">REORDER CONTROL</span><h2>Low stock alerts</h2></div><span>{data.lowStock.length} items</span></div>{!data.lowStock.length?<p>No products are currently at or below their reorder level.</p>:<div className="adminTableWrap"><table className="adminTable"><thead><tr><th>Brand / Part</th><th>Stock</th><th>Reorder level</th><th>Suggested order</th><th>Update</th></tr></thead><tbody>{data.lowStock.map(p=><LowRow key={p.id} p={p} busy={busy} save={(level,qty)=>post('/api/admin/operations',{action:'SET_REORDER',productId:p.id,reorderLevel:level,reorderQuantity:qty})}/>)}</tbody></table></div>}</div>
 <div className="opsSplit"><div className="panel"><h2>Recent purchase orders</h2>{data.purchaseOrders.length?data.purchaseOrders.map(x=><div className="opsList" key={x.id}><div><b>{x.po_no}</b><span>{x.supplier_name||'Supplier'} · {x.status}{x.expected_date?` · ETA ${new Date(x.expected_date).toLocaleDateString()}`:''}</span></div><strong>KSh {Number(x.total_cost||0).toLocaleString()}</strong></div>):<p>No purchase orders yet.</p>}</div><div className="panel"><h2>Employee access</h2>{staff.staff?.length?staff.staff.map(x=><StaffAccountRow key={x.id} account={x} roles={staff.roles} busy={busy} save={body=>post('/api/admin/staff',body)}/>):<p>No employee accounts yet.</p>}</div></div>
 </>}
 </div></section><style jsx>{`.opsGrid{display:grid;grid-template-columns:repeat(3,1fr);gap:16px;margin-bottom:18px}.opsCard{display:grid;gap:10px}.opsCard h2{margin:0}.opsCard input,.opsCard select,.opsCard textarea{width:100%;background:#090c10;color:#edf1f5;border:1px solid #323a44;border-radius:6px;padding:11px}.opsRow{display:grid;grid-template-columns:1fr 1fr;gap:8px}.opsSplit{display:grid;grid-template-columns:1fr 1fr;gap:16px;margin-top:18px}.opsList{display:flex;justify-content:space-between;gap:15px;padding:11px 0;border-bottom:1px solid #252d35}.opsList b,.opsList span{display:block}.opsList span{color:#7f8a95;font-size:11px;margin-top:3px}.adminTableWrap{overflow:auto}.adminTable{width:100%;border-collapse:collapse;min-width:720px}.adminTable th,.adminTable td{text-align:left;padding:12px 10px;border-bottom:1px solid #252d35;font-size:12px}.adminTable th{font-size:10px;color:#7f8a95;text-transform:uppercase}.adminHeading{display:flex;justify-content:space-between;align-items:center}.adminError{border-color:#8b3434}@media(max-width:900px){.opsGrid{grid-template-columns:1fr}.opsSplit{grid-template-columns:1fr}.opsRow{grid-template-columns:1fr}}`}</style></Layout>;
}
function LowRow({p,busy,save}){const [level,setLevel]=useState(p.reorder_level),[qty,setQty]=useState(p.reorder_quantity);return <tr><td><b>{p.brand}</b><br/><small>{p.part_no} · {p.name}</small></td><td>{p.stock}</td><td><input style={{width:80}} type="number" min="0" value={level} onChange={e=>setLevel(e.target.value)}/></td><td><input style={{width:90}} type="number" min="1" value={qty} onChange={e=>setQty(e.target.value)}/></td><td><button disabled={busy} onClick={()=>save(Number(level),Number(qty))}>Save</button></td></tr>}

function StaffAccountRow({account,roles,busy,save}){
 const [role,setRole]=useState(account.role),[password,setPassword]=useState('');
 return <section aria-label={'Staff account '+account.email} style={{padding:'16px 0',borderBottom:'1px solid #304427'}}>
  <strong>{account.name}</strong><p>{account.email} · Current role: {account.role.replaceAll('_',' ')}</p>
  {account.role!=='admin'&&<>
   <label>Staff role <select aria-label={'Role for '+account.email} value={role} onChange={e=>setRole(e.target.value)}>{roles.map(r=><option key={r} value={r}>{r.replaceAll('_',' ')}</option>)}</select></label>
   <button disabled={busy||role===account.role} onClick={()=>save({action:'SET_ROLE',id:account.id,role})}>Save role for {account.email}</button>
   <form onSubmit={e=>{e.preventDefault();save({action:'RESET_PASSWORD',id:account.id,password});setPassword('');}}>
    <label>New temporary password<input aria-label={'New password for '+account.email} type="password" autoComplete="new-password" minLength={12} required value={password} onChange={e=>setPassword(e.target.value)}/></label>
    <button disabled={busy||password.length<12}>Reset password for {account.email}</button>
   </form>
  </>}
 </section>;
}
