import {useEffect,useRef,useState} from 'react';
import Layout from '../components/Layout';
import FinanceLedger from '../components/FinanceLedger';
import FinanceAnalysis from '../components/FinanceAnalysis';
const money=n=>'KSh '+Number(n||0).toLocaleString('en-KE');
const day=d=>String(d||'').slice(0,10);
export default function Receivables(){
 const [data,setData]=useState(null),[error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false),[client,setClient]=useState({name:'',contact:''}),[customer,setCustomer]=useState(''),[part,setPart]=useState(''),[quantity,setQuantity]=useState(1),[lines,setLines]=useState([]),[credit,setCredit]=useState({clientId:'',limitKes:'',note:''}),[invoice,setInvoice]=useState({quoteId:'',termsDays:'0'}),[payment,setPayment]=useState({invoiceId:'',amountKes:'',method:'Bank',reference:'',receivedOn:''}),[selected,setSelected]=useState(null),[voidNote,setVoidNote]=useState('');
 const keys=useRef(new Map());
 async function load(){const r=await fetch('/api/receivables',{cache:'no-store'});const j=await r.json();if(!r.ok)throw Error(j.error);setData(j);}
 useEffect(()=>{load().catch(e=>setError(e.message));},[]);
 async function send(body,reset){setBusy(true);setError('');setNotice('');const json=JSON.stringify(body);if(!keys.current.has(json))keys.current.set(json,crypto.randomUUID());try{const r=await fetch('/api/receivables',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...body,requestKey:keys.current.get(json)})});const j=await r.json();if(!r.ok)throw Error(j.error);await load();reset?.();setNotice('Saved. Open Document history to view or print documents.');return true;}catch(e){setError(e.message);return false;}finally{setBusy(false);}}
 const role=data?.user.role,selling=['admin','cashier'].includes(role),collecting=['admin','finance'].includes(role);
 const total=lines.reduce((sum,l)=>sum+l.priceKes*l.quantity,0),doc=data?.documents?.find(d=>String(d.id)===String(selected));
 function addLine(){const p=data.products.find(p=>String(p.id)===part);const qty=Number(quantity);if(!p||!Number.isInteger(qty)||qty<1||qty>10000)return;setLines(old=>{const i=old.find(x=>String(x.id)===part);return i?old.map(x=>String(x.id)===part?{...x,quantity:Math.min(10000,x.quantity+qty)}:x):[...old,{id:Number(p.id),name:p.name,priceKes:Number(p.price_kes),quantity:qty}];});}
 const choices=data?.clients?.map(c=><option key={c.id} value={c.id}>{c.name} · credit limit {money(c.credit_limit_kes)}</option>);
 return <Layout title="Sales & finance | Shilatech" noindex><section className="counterShell receivables"><h1>Sales &amp; customer accounts</h1>
 <p>Quotations, commercial invoices and recorded collections. This register does not reserve or dispatch stock, create POS sales, charge customers or transmit invoices to KRA.</p><p><a href="https://www.kra.go.ke/online-services/etims" target="_blank" rel="noreferrer">eTIMS integration is required separately</a>. Use sample transactions while testing. Do not add these figures to POS sales without reconciliation.</p>
 {error&&<p role="alert">{error}</p>}{notice&&<p role="status">{notice}</p>}
 {!data&&<p>Loading finance access…</p>}
 {data&&!data.ready&&<article className="panel"><h2>Enable sales and finance records</h2><p>Creates empty records only; no stock, salaries or existing sales are changed.</p>{role==='admin'?<button disabled={busy} onClick={()=>send({action:'SETUP'})}>Initialise sales and finance</button>:<p>Ask the administrator to initialise this module.</p>}</article>}
 {data?.ready&&<>
 {(selling||collecting)&&<form className="panel" onSubmit={e=>{e.preventDefault();send({action:'CLIENT',...client},()=>setClient({name:'',contact:''}));}}><h2>Add account customer</h2><p>New customers have no approved credit. Sales staff see customers and documents they created.</p><label>Customer / company name<input required maxLength={160} value={client.name} onChange={e=>setClient({...client,name:e.target.value})}/></label><label>Contact details<input required maxLength={300} value={client.contact} onChange={e=>setClient({...client,contact:e.target.value})}/></label><button disabled={busy}>Create customer</button></form>}
 {role==='admin'&&<form className="panel" onSubmit={e=>{e.preventDefault();send({action:'CREDIT',...credit});}}><h2>Approve customer credit</h2><p>Only the administrator can approve a limit for 30-day terms. A zero limit prevents new credit invoices; existing debts remain payable.</p><label>Customer<select required value={credit.clientId} onChange={e=>setCredit({...credit,clientId:e.target.value})}><option value="">Select customer</option>{choices}</select></label><label>Credit limit (whole KSh)<input required type="number" min="0" step="1" value={credit.limitKes} onChange={e=>setCredit({...credit,limitKes:e.target.value})}/></label><label>Approval reason<textarea required maxLength={1000} value={credit.note} onChange={e=>setCredit({...credit,note:e.target.value})}/></label><button disabled={busy}>Approve credit limit</button></form>}
 {selling&&<><form className="panel" onSubmit={e=>{e.preventDefault();send({action:'QUOTE',clientId:customer,items:lines.map(({id,quantity})=>({id,quantity})),expectedTotalKes:total},()=>setLines([]));}}><h2>Create quotation</h2><label>Customer<select required value={customer} onChange={e=>setCustomer(e.target.value)}><option value="">Select customer</option>{choices}</select></label><label>Catalogue part<select value={part} onChange={e=>setPart(e.target.value)}><option value="">Choose a part</option>{data.products.map(p=><option key={p.id} value={p.id}>{p.part_no} · {p.name} · {money(p.price_kes)}</option>)}</select></label><label>Quantity<input type="number" min="1" max="10000" step="1" value={quantity} onChange={e=>setQuantity(e.target.value)}/></label><button type="button" disabled={busy||!part||lines.length>=50} onClick={addLine}>Add part to quotation</button>{lines.map(l=><p key={l.id}>{l.name} × {l.quantity} · {money(l.priceKes*l.quantity)} <button type="button" onClick={()=>setLines(lines.filter(i=>i.id!==l.id))}>Remove {l.name}</button></p>)}<p>Total: <strong>{money(total)}</strong></p><p>Valid for 14 days. Catalogue prices only; no manual discounts. Stock is not reserved.</p><button disabled={busy||!lines.length}>Save quotation</button></form>
 <form className="panel" onSubmit={e=>{e.preventDefault();send({action:'INVOICE',...invoice},()=>setInvoice({quoteId:'',termsDays:'0'}));}}><h2>Create invoice from quotation</h2><label>Quotation<select required value={invoice.quoteId} onChange={e=>setInvoice({...invoice,quoteId:e.target.value})}><option value="">Select quotation</option>{data.documents.filter(d=>d.kind==='QUOTE'&&d.status==='OPEN'&&!d.invoice_id).map(d=><option key={d.id} value={d.id}>{d.number} · {d.client_name} · {money(d.total_kes)}</option>)}</select></label><label>Payment terms<select value={invoice.termsDays} onChange={e=>setInvoice({...invoice,termsDays:e.target.value})}><option value="0">Payment on issue</option><option value="30">30 days — approved credit customers only</option></select></label><p>Credit is checked when saving. This creates an internal commercial invoice; it does not issue stock or create a tax invoice.</p><button disabled={busy}>Issue commercial invoice</button></form></>}
 {collecting&&<form className="panel" onSubmit={e=>{e.preventDefault();if(window.confirm('Confirm this payment has already been received and has not been recorded against this invoice. No money will be transferred.'))send({action:'PAYMENT',...payment},()=>setPayment({...payment,amountKes:'',reference:''}));}}><h2>Record invoice payment</h2><label>Outstanding invoice<select required value={payment.invoiceId} onChange={e=>setPayment({...payment,invoiceId:e.target.value})}><option value="">Select invoice</option>{data.documents.filter(d=>d.kind==='INVOICE'&&d.status==='OPEN'&&Number(d.balance_kes)>0).map(d=><option key={d.id} value={d.id}>{d.number} · {d.client_name} · due {money(d.balance_kes)}</option>)}</select></label><label>Amount received (whole KSh)<input required type="number" min="1" step="1" value={payment.amountKes} onChange={e=>setPayment({...payment,amountKes:e.target.value})}/></label><label>Method<select value={payment.method} onChange={e=>setPayment({...payment,method:e.target.value})}>{['Bank','M-Pesa','Cash','Card'].map(m=><option key={m}>{m}</option>)}</select></label><label>Payment reference / cash voucher<input required maxLength={120} value={payment.reference} onChange={e=>setPayment({...payment,reference:e.target.value})}/></label><label>Date received<input required type="date" value={payment.receivedOn} onChange={e=>setPayment({...payment,receivedOn:e.target.value})}/></label><button disabled={busy}>Record received payment</button></form>}
 <section className="panel"><h2>Document history</h2><p>Latest 200 documents · {role==='cashier'?'your documents only':'all salespeople'}. Issued documents are immutable; the administrator may void unpaid documents with a recorded reason.</p>{!data.documents.length&&<p>No documents yet.</p>}{data.documents.map(d=><p key={d.id}><button onClick={()=>{setSelected(d.id);setVoidNote('');}}>{d.kind} · {d.client_name} · {money(d.total_kes)} · {d.status}{d.overdue?' · OVERDUE':''}</button><small>{d.number} · {d.salesperson_name}</small></p>)}
 {doc&&<><article id="commercial-document"><img src="/shilatech-logo.webp" alt="Shilatech Auto Spares" width="120"/><h3>{doc.kind==='QUOTE'?'QUOTATION':'COMMERCIAL INVOICE'} {doc.status==='VOID'?'— VOID':''}</h3><p>{doc.number}</p><p>Customer: {doc.client_name}<br/>{doc.client_contact}</p><p>Salesperson: {doc.salesperson_name}<br/>Issued: {day(doc.issued_on)} · {doc.kind==='QUOTE'?'Valid until':'Payment due'}: {day(doc.due_on)}</p><table><thead><tr><th>Part</th><th>Qty</th><th>Unit KSh</th><th>Total KSh</th></tr></thead><tbody>{doc.lines.map(l=><tr key={l.id}><td>{l.partNo} · {l.name}</td><td>{l.quantity}</td><td>{l.priceKes}</td><td>{l.totalKes}</td></tr>)}</tbody></table><p><strong>Total: {money(doc.total_kes)}</strong>{doc.kind==='INVOICE'&&<><br/>Recorded paid: {money(doc.paid_kes)} · Balance: {money(doc.balance_kes)}<br/>Terms: {doc.terms_days===30?'30 days':'Payment on issue'}</>}</p><p>Internal commercial record — not an eTIMS tax invoice. No tax breakdown is calculated here. Stock reservation, dispatch and insurer/bank integrations are not performed by this document.</p></article><button className="noPrint" onClick={async()=>{try{await document.querySelector('#commercial-document img').decode();await document.fonts.ready;window.print();}catch{setError('The company logo could not load. Reload before printing.');}}}>Print / save document as PDF</button>{role==='admin'&&doc.status==='OPEN'&&Number(doc.paid_kes)===0&&!doc.invoice_id&&<form className="noPrint" onSubmit={e=>{e.preventDefault();send({action:'VOID',id:doc.id,note:voidNote});}}><label>Reason for voiding<textarea required maxLength={1000} value={voidNote} onChange={e=>setVoidNote(e.target.value)}/></label><button disabled={busy}>Void unpaid document</button></form>}</>}
 </section>
 <section className="panel"><h2>Receivables reports</h2><p>This register only; excludes POS and online sales. All figures below exclude void documents. Recorded collections are not bank-verified.</p><div className="stats">{Object.entries(data.totals).map(([k,v])=><div key={k}><strong>{k}</strong><p>{money(v)}</p></div>)}</div>
 {Number(data.totals.invoiced)>0?<div className="collectionChart"><div role="img" aria-label={'Collections '+money(data.totals.collected)+'; outstanding '+money(data.totals.outstanding)} className="pie" style={{background:`conic-gradient(#70c342 0 ${Number(data.totals.collected)/Number(data.totals.invoiced)*100}%,#a78430 0 100%)`}}/><p>Green: recorded collections<br/>Gold: outstanding balance</p></div>:<p>No invoiced amounts to chart yet.</p>}
 <h3>Invoice value by month (last six months)</h3>{!data.monthly.length&&<p>No invoices in this period.</p>}{data.monthly.map(m=><div key={m.month}><span>{m.month} · {money(m.amount)}</span><div className="bar" style={{width:Math.max(2,Number(m.amount)/Math.max(...data.monthly.map(x=>Number(x.amount)))*100)+'%'}}/></div>)}
 <h3>Recent payment records</h3>{!data.payments.length&&<p>No payments recorded.</p>}{data.payments.map(p=><p key={p.id}>{day(p.received_on)} · {p.number} · {money(p.amount_kes)} · {p.method} · {p.reference}</p>)}</section>
 </>}
 {role&&<FinanceLedger role={role}/>} {role&&<FinanceAnalysis role={role}/>} 
 <style jsx>{`.receivables{color:#e7ede4;line-height:1.65}h1,h2,h3,a{color:#83ce51}.panel{margin:20px 0;padding:22px;border:1px solid #39512e;border-radius:10px;max-width:1000px}label{display:block;margin:14px 0}input,textarea,select{display:block;width:100%;padding:10px;box-sizing:border-box;background:#101910;border:1px solid #53654b;color:white}button{padding:11px 16px;background:#65bd35;border:0;color:#071003;cursor:pointer;margin:4px}button:disabled{opacity:.5;cursor:not-allowed}small{display:block;overflow-wrap:anywhere}table{width:100%;border-collapse:collapse}td,th{text-align:left;padding:8px;border-bottom:1px solid #39512e}.stats{display:flex;flex-wrap:wrap;gap:24px}.stats strong{text-transform:capitalize}.collectionChart{display:flex;align-items:center;gap:24px}.pie{width:140px;height:140px;border-radius:50%;flex-shrink:0}.bar{height:18px;background:#70c342;margin:4px 0 16px}#commercial-document{background:#fff;color:#111;padding:22px}#commercial-document h3{color:#111}`}</style>
 <style jsx global>{`@media print{body *{visibility:hidden}body:has(#commercial-document) *:not(:has(#commercial-document)):not(#commercial-document):not(#commercial-document *){display:none!important}body *:has(#commercial-document){margin:0!important;padding:0!important;min-height:0!important;border:0!important;background:white!important}#commercial-document,#commercial-document *{visibility:visible;color:black!important;background:white!important}#commercial-document{padding:10mm!important;font-size:10pt;overflow-wrap:anywhere}.noPrint{display:none!important}}`}</style>
 </section></Layout>;
}
