import { useEffect,useRef,useState } from 'react';
import Link from 'next/link';
import Layout from '../components/Layout';
const transitions={BOOKED:['INSPECTION'],INSPECTION:['AWAITING_CUSTOMER','IN_PROGRESS'],AWAITING_CUSTOMER:['IN_PROGRESS'],IN_PROGRESS:['READY'],READY:['COMPLETED'],COMPLETED:[],CANCELLED:[]};
const blank={customerName:'',phone:'',vehicle:'',registration:'',service:'',preferredDate:''};
export default function StaffGarage(){
 const [data,setData]=useState(null),[form,setForm]=useState(blank),[notes,setNotes]=useState({}),[error,setError]=useState(''),[busy,setBusy]=useState(false),[message,setMessage]=useState('');
 const bookingKey=useRef(null),sending=useRef(false);
 async function load(){try{const r=await fetch('/api/staff-garage');const j=await r.json();if(!r.ok)throw new Error(j.error);setData(j);}catch(e){setError(e.message);}}
 useEffect(()=>{load();},[]);
 async function send(body){if(sending.current)return;sending.current=true;setBusy(true);setError('');setMessage('');try{const r=await fetch('/api/staff-garage',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const j=await r.json();if(!r.ok)throw new Error(j.error);if(body.action==='CREATE'){setForm(blank);bookingKey.current=null;}setNotes(n=>({...n,[body.id]:''}));setMessage('Job card saved.');await load();}catch(e){setError(e.message);}finally{sending.current=false;setBusy(false);}}
 const readOnly=data?.user.role==='general_manager';
 return <Layout title="Garage staff | Shilatech" noindex><section className="counterShell"><h1>Garage bookings &amp; job cards</h1><p>Enter bookings received through WhatsApp or at the counter. Track work here; this does not import WhatsApp messages.</p><p className="staffHint">Parts required can be recorded in job notes. Issue or sell parts through the authorised warehouse/POS workflow. Garage notes do not change stock or charge a customer.</p><Link href="/approvals">Request a correction, cancellation or reopening</Link>{error&&<p role="alert" className="staffError">{error}</p>}{message&&<p role="status" className="staffSuccess">{message}</p>}{!data?<p>Loading jobs…</p>:<>{readOnly?<p className="staffReadOnly">General manager: read-only access.</p>:<details className="staffRecord" open><summary><strong>New booking</strong></summary><form className="staffForm" onSubmit={e=>{e.preventDefault();bookingKey.current||=crypto.randomUUID();send({action:'CREATE',...form,requestKey:bookingKey.current});}}><div className="staffGrid">{[['customerName','Customer name'],['phone','Phone'],['vehicle','Vehicle / model'],['registration','Registration or VIN'],['service','Requested service'],['preferredDate','Preferred date']].map(([key,label])=><label key={key}>{label}<input type={key==='preferredDate'?'date':'text'} maxLength={key==='service'?1000:200} required={key!=='preferredDate'} value={form[key]} onChange={e=>{setForm({...form,[key]:e.target.value});bookingKey.current=null;}} disabled={busy}/></label>)}</div><button className="button primary" disabled={busy}>Create booking &amp; job card</button></form></details>}
 <h2>Job cards ({data.jobs.length})</h2>{!data.jobs.length&&<p>No garage jobs yet. Add your first booking above.</p>}{data.jobs.map(job=><article className="staffRecord" key={job.id}><div className="staffActions"><h3>{job.job_no} · {job.registration}</h3><span className="staffTag">{job.status.replaceAll('_',' ')}</span></div><p><strong>{job.customer_name}</strong> · {job.phone}<br/>{job.vehicle} · {job.service}</p><p className="staffHint">Record ID {job.id} · Preferred date: {job.preferred_date?String(job.preferred_date).slice(0,10):'Not set'}</p><div className="staffNotes">{job.notes.map(n=><p className="staffNote" key={n.id}>{n.note}<br/><small>{n.employee} · {new Date(n.created_at).toLocaleString('en-KE')}</small></p>)}</div>{!readOnly&&<><label className="staffForm">Progress / parts-required note<textarea maxLength={2000} value={notes[job.id]||''} onChange={e=>setNotes({...notes,[job.id]:e.target.value})} placeholder="Work completed, customer authorisation reference, or parts required"/></label><div className="staffActions"><button disabled={busy||!notes[job.id]?.trim()} onClick={()=>send({action:'NOTE',id:job.id,version:job.version,note:notes[job.id]})}>Add note</button>{transitions[job.status].map(status=><button className="button primary" disabled={busy||!notes[job.id]?.trim()} key={status} onClick={()=>send({action:'PROGRESS',id:job.id,version:job.version,status,note:notes[job.id]})}>Move to {status.replaceAll('_',' ')}</button>)}</div></>}</article>)}</>}</section></Layout>;
}
