#!/usr/bin/env python3
"""Check that every text run in the Shilatech deck is readable on what sits behind it.

The deck is generated by scripts/generate_corporate_presentation.py, which paints
the slides in a light "paper" palette and then recolours panels and lettering to the
dark website theme in one pass. If a colour is left out of that pass, light-theme
lettering ends up dark-on-dark and the slide looks empty in PowerPoint or WPS.
This script catches that class of mistake, and any other low-contrast text.

Requires python-pptx (e.g. pip install python-pptx==1.0.2).
Run from repository root: python scripts/check_presentation_contrast.py
Exits non-zero when any run is below the WCAG contrast floor for its text size.
"""
import sys
from pathlib import Path

from pptx import Presentation
from pptx.util import Inches

NS = '{http://schemas.openxmlformats.org/drawingml/2006/main}'
SRGB = NS + 'srgbClr'
RPR = NS + 'rPr'
PPR = NS + 'pPr'

# WCAG 2.1 minimum contrast: 4.5:1 for body text, 3:1 for large text.
FLOOR_NORMAL = 4.5
FLOOR_LARGE = 3.0
# Shapes thinner than this in either direction are hairline rules/accent bars,
# not the panel a label is actually painted on.
MIN_PANEL = Inches(0.15)


def relative_luminance(hex_colour):
    def channel(value):
        value /= 255
        return value / 12.92 if value <= 0.03928 else ((value + 0.055) / 1.055) ** 2.4
    r, g, b = (channel(int(hex_colour[i:i + 2], 16)) for i in (0, 2, 4))
    return 0.2126 * r + 0.7152 * g + 0.0722 * b


def contrast(a, b):
    la, lb = relative_luminance(a), relative_luminance(b)
    high, low = max(la, lb), min(la, lb)
    return (high + 0.05) / (low + 0.05)


def solid_fill_rgb(fill):
    """'#RRGGBB' as a bare hex string when the fill is a solid sRGB colour."""
    try:
        if fill.type is None or int(fill.type) != 1:  # MSO_FILL_TYPE.SOLID == 1
            return None
        return str(fill.fore_color.rgb)
    except (AttributeError, TypeError, ValueError):
        return None


def first_srgb(element):
    """First explicit <a:srgbClr val="..."> below an rPr or defRPr element."""
    if element is None:
        return None
    for node in element.iter(SRGB):
        return node.get('val')
    return None


def run_colour(run, paragraph):
    """(hex, origin) of a run's colour: its own rPr, else the paragraph defRPr."""
    value = first_srgb(run._r.find(RPR))
    if value:
        return value, 'run'
    ppr = paragraph._p.find(PPR)
    def_rpr = None if ppr is None else ppr.find(NS + 'defRPr')
    value = first_srgb(def_rpr)
    if value:
        return value, 'paragraph'
    return None, 'inherited'


def bounds(shape):
    left, top = shape.left or 0, shape.top or 0
    return left, top, left + (shape.width or 0), top + (shape.height or 0)


def sample_points(rect, per_axis=5):
    """A grid of points covering the text box, so straddled panels are caught."""
    left, top, right, bottom = rect
    points = []
    for i in range(per_axis):
        for j in range(per_axis):
            points.append((left + (right - left) * (i + 0.5) / per_axis,
                           top + (bottom - top) * (j + 0.5) / per_axis))
    return points


def backgrounds(slide, shapes, rects, upto):
    """Worst-case painted colour behind each sample point of a text box."""
    base = solid_fill_rgb(slide.background.fill) or 'FFFFFF'
    for point in sample_points(rects[upto]):
        colour = base
        for below in range(upto - 1, -1, -1):
            rect = rects[below]
            if rect is None:
                continue
            left, top, right, bottom = rect
            if not (left <= point[0] <= right and top <= point[1] <= bottom):
                continue
            if right - left < MIN_PANEL or bottom - top < MIN_PANEL:
                continue  # hairline rule, not the panel behind the text
            fill = solid_fill_rgb(shapes[below].fill)
            if fill:
                colour = fill
                break
        yield colour


def audit(path):
    prs = Presentation(path)
    problems, worst, checked = [], (99.0, None), 0
    for number, slide in enumerate(prs.slides, start=1):
        shapes = list(slide.shapes)
        rects = [bounds(s) for s in shapes]
        for index, shape in enumerate(shapes):
            if not shape.has_text_frame or not shape.text_frame.text.strip():
                continue
            for paragraph in shape.text_frame.paragraphs:
                for run in paragraph.runs:
                    if not run.text.strip():
                        continue
                    colour, origin = run_colour(run, paragraph)
                    try:
                        size = run.font.size.pt if run.font.size else 18.0
                        bold = bool(run.font.bold)
                    except (AttributeError, TypeError):
                        size, bold = 18.0, False
                    floor = FLOOR_LARGE if (size >= 18 or (size >= 14 and bold)) else FLOOR_NORMAL
                    if colour is None:
                        problems.append((number, run.text[:40], 'no explicit colour',
                                         '-', 0.0, floor))
                        continue
                    behind = min(backgrounds(slide, shapes, rects, index),
                                 key=lambda bg: contrast(colour, bg))
                    ratio = contrast(colour, behind)
                    checked += 1
                    if worst[1] is None or ratio < worst[0]:
                        worst = (ratio, f'slide {number}: {run.text[:32]!r}')
                    if ratio < floor:
                        problems.append((number, run.text[:40], f'#{colour} ({origin})',
                                         f'#{behind}', ratio, floor))
    print(f'{path}: {len(prs.slides)} slides, {checked} text runs checked')
    print(f'lowest contrast: {worst[0]:.2f}:1  ({worst[1]})')
    if problems:
        print(f'\n{len(problems)} run(s) below the contrast floor:')
        for number, text, colour, behind, ratio, floor in problems:
            print(f'  slide {number:>2}  {text!r:<42} text={colour:<22} '
                  f'behind={behind:<9} ratio={ratio:.2f} (needs {floor})')
        return 1
    print('all text meets the WCAG contrast floor for its size')
    return 0


def main(argv):
    target = Path(argv[1]) if len(argv) > 1 else \
        Path(__file__).resolve().parents[1] / 'docs' / 'Shilatech_Corporate_Presentation.pptx'
    if not target.exists():
        print(f'not found: {target}\nrun scripts/generate_corporate_presentation.py first')
        return 2
    return audit(str(target))


if __name__ == '__main__':
    sys.exit(main(sys.argv))
